/**
 * <copyright>
 * </copyright>
 *
 * $Id: ItemValidator.java,v 1.1 2007/02/08 23:09:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.epo2.validation;

import java.util.Date;

import org.eclipse.emf.teneo.samples.emf.sample.epo2.PurchaseOrder;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.epo2.Item}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemValidator {
	boolean validate();

	boolean validateOrder(PurchaseOrder value);
	boolean validateProductName(String value);
	boolean validateQuantity(int value);
	boolean validateUSPrice(int value);
	boolean validateComment(String value);
	boolean validateShipDate(Date value);
	boolean validatePartNum(String value);
}
