/**
 * <copyright>
 * </copyright>
 *
 * $Id: PurchaseOrderValidator.java,v 1.1 2007/02/08 23:09:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.epo2.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.sample.epo2.Address;
import org.eclipse.emf.teneo.samples.emf.sample.epo2.Customer;
import org.eclipse.emf.teneo.samples.emf.sample.epo2.Item;
import org.eclipse.emf.teneo.samples.emf.sample.epo2.OrderStatus;
import org.eclipse.emf.teneo.samples.emf.sample.epo2.PurchaseOrder;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.epo2.PurchaseOrder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PurchaseOrderValidator {
	boolean validate();

	boolean validateItems(EList<Item> value);
	boolean validateBillTo(Address value);
	boolean validateShipTo(Address value);
	boolean validateComment(String value);
	boolean validateOrderDate(Date value);
	boolean validateStatus(OrderStatus value);
	boolean validateTotalAmount(int value);
	boolean validateCustomer(Customer value);
	boolean validatePreviousOrder(PurchaseOrder value);
}
