/**
 * <copyright>
 * </copyright>
 *
 * $Id: DepartmentValidator.java,v 1.1 2008/04/23 15:45:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.employee.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.sample.employee.Employee;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.employee.Department}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DepartmentValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateEmployees(EList<Employee> value);
}
