/**
 * <copyright>
 * </copyright>
 *
 * $Id: EmployeeValidator.java,v 1.1 2008/04/23 15:45:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.employee.validation;

import java.util.Date;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.employee.Employee}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EmployeeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSalary(int value);
	boolean validateAge(int value);
	boolean validateHireDate(Date value);
}
