/**
 * <copyright>
 * </copyright>
 *
 * $Id: TestAnyValidator.java,v 1.1 2007/02/08 23:09:25 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.anytype.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.anytype.TestAny}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestAnyValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSingleAnyType(EObject value);
	boolean validateMultiAnyType(EList<EObject> value);
	boolean validateMyAny(FeatureMap value);
	boolean validateAny(FeatureMap value);
}
