/**
 * <copyright>
 * </copyright>
 *
 * $Id: ItemValidator.java,v 1.1 2007/02/08 23:09:17 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.schemaprimerpo.validation;

import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.schemaprimerpo.Item}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemValidator {
	boolean validate();

	boolean validateProductName(String value);
	boolean validateQuantity(BigInteger value);
	boolean validateUSPrice(BigDecimal value);
	boolean validateComment(String value);
	boolean validateShipDate(Object value);
	boolean validatePartNum(String value);
}
