/**
 * <copyright>
 * </copyright>
 *
 * $Id: PurchaseOrderValidator.java,v 1.1 2007/02/08 23:09:17 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.schemaprimerpo.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.sample.schemaprimerpo.Item;
import org.eclipse.emf.teneo.samples.emf.sample.schemaprimerpo.USAddress;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.schemaprimerpo.PurchaseOrder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PurchaseOrderValidator {
	boolean validate();

	boolean validateShipTo(USAddress value);
	boolean validateBillTo(USAddress value);
	boolean validateComment(String value);
	boolean validateItems(EList<Item> value);
	boolean validateOrderDate(Object value);
}
