/**
 * <copyright>
 * </copyright>
 *
 * $Id: USAddressValidator.java,v 1.1 2007/02/08 23:09:17 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.schemaprimerpo.validation;

import java.math.BigDecimal;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.schemaprimerpo.USAddress}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface USAddressValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateStreet(String value);
	boolean validateCity(String value);
	boolean validateState(String value);
	boolean validateZip(BigDecimal value);
	boolean validateCountry(String value);
}
