/**
 * <copyright>
 * </copyright>
 *
 * $Id: TestDateValidator.java,v 1.1 2007/03/04 21:18:10 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.datetime.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.datetime.TestDate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestDateValidator {
	boolean validate();

	boolean validateDate(Object value);
	boolean validateDatetime(Object value);
}
