/**
 * <copyright>
 * </copyright>
 *
 * $Id: AValidator.java,v 1.1 2007/02/08 23:09:25 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.anytype.validation;

import org.eclipse.emf.teneo.samples.emf.schemaconstructs.anytype.B;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.anytype.A}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDoub(double value);
	boolean validateLon(long value);
	boolean validateMyB(B value);
}
