/**
 * <copyright>
 * </copyright>
 *
 * $Id: BookDefinitionValidator.java,v 1.1 2007/12/13 06:52:44 mtaal Exp $
 */
package com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.validation;

/**
 * A sample validator interface for
 * {@link com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.BookDefinition}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BookDefinitionValidator {
	boolean validate();

	boolean validateDescription(String value);

	boolean validateLocation(String value);

	boolean validateUniqueName(String value);
}
