/**
 * <copyright>
 * </copyright>
 *
 * $Id: DocumentRootValidator.java,v 1.1 2007/12/13 06:52:43 mtaal Exp $
 */
package com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.validation;

import com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.AdultBooks;
import com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.BookDefinition;
import com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.BooksInLib;
import com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.ChildrenBooks;
import com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.PublisherDefinition;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for
 * {@link com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.DocumentRoot}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);

	boolean validateXMLNSPrefixMap(EMap<String, String> value);

	boolean validateXSISchemaLocation(EMap<String, String> value);

	boolean validateAbstractBookDefinition(BookDefinition value);

	boolean validateAdultBooks(AdultBooks value);

	boolean validateBooksinlib(BooksInLib value);

	boolean validateChildrenBooks(ChildrenBooks value);

	boolean validatePublisherDefinition(PublisherDefinition value);
}
