/**
 * <copyright>
 * </copyright>
 *
 * $Id: LibraryValidator.java,v 1.1 2007/12/13 06:52:44 mtaal Exp $
 */
package com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.validation;

import com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.BookDefinition;
import com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.Library;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for
 * {@link com.ibm.websphere.appserver.schemas._6._0.ibm.portal.test.Library}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LibraryValidator {
	boolean validate();

	boolean validateLibrary(EList<Library> value);

	boolean validateAbstractBookDefinitionGroup(FeatureMap value);

	boolean validateAbstractBookDefinition(EList<BookDefinition> value);

	boolean validateUniqueName(String value);
}
