/**
 * <copyright>
 * </copyright>
 *
 * $Id: NavigationElementValidator.java,v 1.1 2008/03/19 22:25:40 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.top.validation;

import org.eclipse.emf.teneo.samples.issues.top.PageParams;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.top.NavigationElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NavigationElementValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateDescription(String value);
	boolean validatePageParams(PageParams value);
	boolean validateUniqueName(String value);
}
