/**
 * <copyright>
 * </copyright>
 *
 * $Id: CSMCharacteristicValueContainerValidator.java,v 1.1 2007/03/07 23:34:07 mtaal Exp $
 */
package datacore.validation;

import datacore.CSMCharacteristicDefinition;
import datacore.CSMInstance;
import datacore.CSMValue;
import datacore.CSMValueSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link datacore.CSMCharacteristicValueContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSMCharacteristicValueContainerValidator {
	boolean validate();

	boolean validateValid(boolean value);
	boolean validateCsmInstance(CSMInstance value);
	boolean validateConcreteValue(CSMValue value);
	boolean validateValueSet(EList<CSMValueSet> value);
	boolean validateDataType(CSMCharacteristicDefinition value);
}
