/**
 * <copyright>
 * </copyright>
 *
 * $Id: CSMCharacteristicDefinitionValidator.java,v 1.1 2007/03/07 23:34:07 mtaal Exp $
 */
package datacore.validation;

import datacore.CSMCharacteristicValueContainer;
import datacore.CSMClass;
import datacore.CSMType;
import datacore.ColumnDefinition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link datacore.CSMCharacteristicDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSMCharacteristicDefinitionValidator {
	boolean validate();

	boolean validateCsmClass(CSMClass value);
	boolean validateCsmCharacteristicType(CSMType value);
	boolean validateUserDefined(boolean value);
	boolean validateName(String value);
	boolean validateValueContainer(EList<CSMCharacteristicValueContainer> value);
	boolean validateAliasName(String value);
	boolean validateIndex(int value);
	boolean validateDataSource(ColumnDefinition value);
	boolean validateFreeParameter(boolean value);
}
