/**
 * <copyright>
 * </copyright>
 *
 * $Id: CSMClassValidator.java,v 1.1 2007/03/07 23:34:07 mtaal Exp $
 */
package datacore.validation;

import datacore.CSMCharacteristicDefinition;
import datacore.CSMInstance;
import datacore.CSMRepresentation;
import datacore.CSMType;
import datacore.DataSourceDefinitions;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link datacore.CSMClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSMClassValidator {
	boolean validate();

	boolean validateCsmCharacteristicDefinitions(EList<CSMCharacteristicDefinition> value);
	boolean validateInstances(EList<CSMInstance> value);
	boolean validateValidCSMTypes(EList<CSMType> value);
	boolean validateDescription(String value);
	boolean validateDatasourceDefinition(DataSourceDefinitions value);
	boolean validateKeyCharachteristicDefinition(CSMCharacteristicDefinition value);
	boolean validateClassRepresentations(EList<CSMRepresentation> value);
}
