/**
 * <copyright>
 * </copyright>
 *
 * $Id: CSMInstanceValidator.java,v 1.1 2007/03/07 23:34:07 mtaal Exp $
 */
package datacore.validation;

import datacore.CSMCharacteristicValueContainer;
import datacore.CSMClass;
import datacore.CSMRepresentationRoot;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link datacore.CSMInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSMInstanceValidator {
	boolean validate();

	boolean validateCsmValueContainer(EList<CSMCharacteristicValueContainer> value);
	boolean validateCsmReprasentation(EList<CSMRepresentationRoot> value);
	boolean validateContainingCSMClass(CSMClass value);
}
