/**
 * <copyright>
 * </copyright>
 *
 * $Id: CSMRepresentationValidator.java,v 1.1 2007/03/07 23:34:07 mtaal Exp $
 */
package datacore.validation;

import datacore.CSMClass;
import datacore.CSMRepresentation;
import datacore.CSMRepresentationRoot;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link datacore.CSMRepresentation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSMRepresentationValidator {
	boolean validate();

	boolean validateParent(CSMRepresentation value);
	boolean validateChildren(EList<CSMRepresentation> value);
	boolean validateValid(boolean value);
	boolean validateRepresentationRoot(CSMRepresentationRoot value);
	boolean validateOwnerCSMClass(CSMClass value);
}
