/**
 * <copyright>
 * </copyright>
 *
 * $Id: CSMRepresentationRootValidator.java,v 1.1 2007/03/07 23:34:07 mtaal Exp $
 */
package datacore.validation;

import datacore.CSMInstance;
import datacore.CSMRepresentation;
import datacore.CSMRepresentationRootDescriptor;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link datacore.CSMRepresentationRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSMRepresentationRootValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateModelName(String value);
	boolean validateCsmInstance(CSMInstance value);
	boolean validateRepresentationTree(CSMRepresentation value);
	boolean validateValueDescriptors(EList<CSMRepresentationRootDescriptor> value);
}
