/**
 * <copyright>
 * </copyright>
 *
 * $Id: CSMRepresentationRootDescriptorValidator.java,v 1.1 2007/03/07 23:34:07 mtaal Exp $
 */
package datacore.validation;

import datacore.CSMRepresentationRoot;

/**
 * A sample validator interface for {@link datacore.CSMRepresentationRootDescriptor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSMRepresentationRootDescriptorValidator {
	boolean validate();

	boolean validateRepresentationRoot(CSMRepresentationRoot value);
	boolean validateCharacteristicID(String value);
	boolean validateCharacteriticValue(String value);
}
