/**
 * <copyright>
 * </copyright>
 *
 * $Id: CSMXMLValidator.java,v 1.1 2007/03/07 23:34:07 mtaal Exp $
 */
package datacore.validation;

import datacore.CSMElement;
import datacore.CSMType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link datacore.CSMXML}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CSMXMLValidator {
	boolean validate();

	boolean validateElements(EList<CSMElement> value);
	boolean validateTypes(EList<CSMType> value);
}
