/**
 * <copyright>
 * </copyright>
 *
 * $Id: AValidator.java,v 1.1 2007/02/08 23:09:20 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.attributes.validation;

import org.eclipse.emf.teneo.samples.emf.schemaconstructs.attributes.R;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.attributes.A}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateB(long value);
	boolean validateC(String value);
	boolean validateComment(double value);
	boolean validateId(String value);
	boolean validateD(String value);
	boolean validateMyR(R value);
}
