/**
 * <copyright>
 * </copyright>
 *
 * $Id: BookValidator.java,v 1.1 2007/02/08 23:09:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.emap.validation;

import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.teneo.samples.emf.schemaconstructs.emap.Writer;
import java.util.Map;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.emap.Book}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BookValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateWriters(EMap<String, Writer> value);

	boolean validateKeyWords(EMap<String, String> value);

	boolean validateCityByWriter(EMap<Writer, String> value);

	boolean validateWriters(Map value);
	boolean validateKeyWords(Map value);
	boolean validateCityByWriter(Map value);
}
