/**
 * <copyright>
 * </copyright>
 *
 * $Id: StringToWriterMapEntryValidator.java,v 1.1 2007/02/08 23:09:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.emap.validation;

import org.eclipse.emf.teneo.samples.emf.schemaconstructs.emap.Writer;

/**
 * A sample validator interface for {@link java.util.Map.Entry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StringToWriterMapEntryValidator {
	boolean validate();

	boolean validateTypedKey(String value);
	boolean validateTypedValue(Writer value);
}
