/**
 * <copyright>
 * </copyright>
 *
 * $Id: ItemListValidator.java,v 1.1 2007/02/08 23:09:23 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.set.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.annotations.set.ContainedItem;
import org.eclipse.emf.teneo.samples.emf.annotations.set.Item;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.set.ItemList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemListValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateContainedItem(EList<ContainedItem> value);
	boolean validateItem(EList<Item> value);
	boolean validateJoinedItem(EList<Item> value);
}
