<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="library"
    nsURI="http:///org/eclipse/emf/teneo/eclipselink/examples/library.ecore" nsPrefix="library">
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//BookCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        eType="#//Writer" eOpposite="#//Writer/books"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" upperBound="-1"
        eType="#//BookStylesMapEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="translator" eType="#//Translator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cover" eType="#//Cover"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writers" upperBound="-1"
        eType="#//Writer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
        eType="#//StringToBookMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Writer" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1"
        eType="#//Book" eOpposite="#//Book/author"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address" eType="#//Address"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishers" upperBound="-1"
        eType="#//Publisher" eOpposite="#//Publisher/writers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typewriters" upperBound="-1"
        eType="#//TypeWriter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BookCategory">
    <eLiterals name="Mystery"/>
    <eLiterals name="ScienceFiction" value="1"/>
    <eLiterals name="Biography" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringToBookMapEntry" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Identifiable">
    <eAnnotations source="teneo.jpa">
      <details key="value" value="@Table(name=&quot;EMFLIB_LIBRARY_BOOK_MAP&quot;)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Book"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address" eSuperTypes="#//Identifiable">
    <eAnnotations source="http://www.oracle.com/toplink/emf/2006/ContainerMapping">
      <details key="eContainingClassName" value="Writer"/>
      <details key="eContainingClassPackageName" value="library"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="town" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writers" upperBound="-1"
        eType="#//Writer" eOpposite="#//Writer/publishers">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@JoinTable(name=&quot;EMFLIB_PUBLISHER_WRITERS&quot;)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookStylesMapEntry" instanceClassName="java.util.Map$Entry"
      eSuperTypes="#//Identifiable">
    <eAnnotations source="teneo.jpa">
      <details key="value" value="@Table(name=&quot;EMFLIB_BOOK_STYLE_MAP&quot;)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Style"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Translator" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address" eType="#//Address"
        containment="true">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Transient"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TWriterType">
    <eLiterals name="Typewriter"/>
    <eLiterals name="Computer" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeWriter" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maker" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TWriterType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cover" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colored" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eAnnotations source="teneo.jpa">
      <details key="value" value="@MappedSuperclass"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Id&#xA;@GeneratedValue"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="teneo.jpa">
        <details key="value" value="@Version"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTest" abstract="true"/>
</ecore:EPackage>
