/**
 * <copyright>
 * </copyright>
 *
 * $Id: CascadeTypeValidator.java,v 1.1 2009/07/23 11:16:28 mtaal Exp $
 */
package org.eclipse.emf.teneo.jpa.orm.validation;

import org.eclipse.emf.teneo.jpa.orm.EmptyType;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.jpa.orm.CascadeType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CascadeTypeValidator {
	boolean validate();

	boolean validateCascadeAll(EmptyType value);
	boolean validateCascadePersist(EmptyType value);
	boolean validateCascadeMerge(EmptyType value);
	boolean validateCascadeRemove(EmptyType value);
	boolean validateCascadeRefresh(EmptyType value);
}
