/**
 * <copyright>
 * </copyright>
 *
 * $Id: EmbeddableValidator.java,v 1.1 2009/07/23 11:16:29 mtaal Exp $
 */
package org.eclipse.emf.teneo.jpa.orm.validation;

import org.eclipse.emf.teneo.jpa.orm.AccessType;
import org.eclipse.emf.teneo.jpa.orm.EmbeddableAttributes;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.jpa.orm.Embeddable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EmbeddableValidator {
	boolean validate();

	boolean validateDescription(String value);
	boolean validateAttributes(EmbeddableAttributes value);
	boolean validateAccess(AccessType value);
	boolean validateClass(String value);
	boolean validateMetadataComplete(boolean value);
}
