/**
 * <copyright>
 * </copyright>
 *
 * $Id: JoinColumnValidator.java,v 1.1 2009/07/23 11:16:29 mtaal Exp $
 */
package org.eclipse.emf.teneo.jpa.orm.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.jpa.orm.JoinColumn}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JoinColumnValidator {
	boolean validate();

	boolean validateColumnDefinition(String value);
	boolean validateInsertable(boolean value);
	boolean validateName(String value);
	boolean validateNullable(boolean value);
	boolean validateReferencedColumnName(String value);
	boolean validateTable(String value);
	boolean validateUnique(boolean value);
	boolean validateUpdatable(boolean value);
}
