/**
 * <copyright>
 * </copyright>
 *
 * $Id: BookValidator.java,v 1.1 2009/09/12 04:47:31 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.bz288963.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.issues.bz288963.Book;
import org.eclipse.emf.teneo.samples.issues.bz288963.Booktype;
import org.eclipse.emf.teneo.samples.issues.bz288963.Paragraph;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.bz288963.Book}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BookValidator {
	boolean validate();

	boolean validateCitation(Book value);
	boolean validateParalist(EList<Paragraph> value);
	boolean validateId(String value);
	boolean validateSelfdef(String value);
	boolean validateType(Booktype value);
}
