/**
 * <copyright>
 * </copyright>
 *
 * $Id: BigTreeValidator.java,v 1.1 2007/07/09 12:55:21 mtaal Exp $
 */
package tc.tree.validation;


/**
 * A sample validator interface for {@link tc.tree.BigTree}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BigTreeValidator {
	boolean validate();

	boolean validateName(String value);
}
