/**
 * <copyright>
 * </copyright>
 *
 * $Id: RoleValidator.java,v 1.2 2007/07/17 17:37:32 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.forcedidbag.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.teneo.samples.emf.annotations.forcedidbag.User;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.forcedidbag.Role}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoleValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateUsers(EList<User> value);
}
