/**
 * <copyright>
 * </copyright>
 *
 * $Id: MainValidator.java,v 1.1 2007/02/08 23:09:19 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.relation.relation1ton.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.relation.relation1ton.OneCN;
import org.eclipse.emf.teneo.samples.emf.relation.relation1ton.OneCR;
import org.eclipse.emf.teneo.samples.emf.relation.relation1ton.OneNN;
import org.eclipse.emf.teneo.samples.emf.relation.relation1ton.OneNR;
import org.eclipse.emf.teneo.samples.emf.relation.relation1ton.TwoCN;
import org.eclipse.emf.teneo.samples.emf.relation.relation1ton.TwoCR;
import org.eclipse.emf.teneo.samples.emf.relation.relation1ton.TwoNN;
import org.eclipse.emf.teneo.samples.emf.relation.relation1ton.TwoNR;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.relation.relation1ton.Main}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MainValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateOnecr(EList<OneCR> value);
	boolean validateOnecn(EList<OneCN> value);
	boolean validateOnenr(EList<OneNR> value);
	boolean validateOnenn(EList<OneNN> value);
	boolean validateTwocr(EList<TwoCR> value);
	boolean validateTwocn(EList<TwoCN> value);
	boolean validateTwonr(EList<TwoNR> value);
	boolean validateTwonn(EList<TwoNN> value);
}
