/**
 * <copyright>
 * </copyright>
 *
 * $Id: SimpleListValidator.java,v 1.1 2007/02/08 23:09:27 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.simpletypes.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.simpletypes.SimpleList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimpleListValidator {
	boolean validate();

	boolean validateCode(String value);
	boolean validateBoo(EList<Boolean> value);
	boolean validateByt(EList<Byte> value);
	boolean validateDoubl(EList<Double> value);
	boolean validateFloa(EList<Float> value);
	boolean validateInte(EList<Integer> value);
	boolean validateLong(EList<Long> value);
	boolean validateShor(EList<Short> value);
	boolean validateDat(EList<Date> value);
	boolean validateLimitedstring(EList<String> value);
	boolean validateIntArray(int[] value);
	boolean validateDoubleArray(double[] value);
	boolean validateStringArray(String[] value);
	boolean validateByteArray(byte[] value);
}
