/**
 * <copyright>
 * </copyright>
 *
 * $Id: EmbedderValidator.java,v 1.1 2007/02/08 23:09:22 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.embedded.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.annotations.embedded.Embeddable;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.embedded.Embedder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EmbedderValidator {
	boolean validate();

	boolean validateFirstEmbedded(Embeddable value);
	boolean validateSecondEmbedded(Embeddable value);
	boolean validateThirdEmbedded(Embeddable value);
	boolean validateFourthEmbedded(EList<Embeddable> value);
	boolean validateFifthEmbedded(Embeddable value);
}
