/**
 * <copyright>
 * </copyright>
 *
 * $Id: ContentListValidator.java,v 1.1 2007/02/08 23:09:22 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.inheritancemapping.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.annotations.inheritancemapping.Address;
import org.eclipse.emf.teneo.samples.emf.annotations.inheritancemapping.Price;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.inheritancemapping.ContentList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContentListValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateAddress(EList<Address> value);
	boolean validatePrice(EList<Price> value);
}
