/**
 * <copyright>
 * </copyright>
 *
 * $Id: ColumnValidator.java,v 1.2 2009/09/13 14:45:54 mtaal Exp $
 */
package org.eclipse.emf.teneo.annotations.pannotation.validation;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.annotations.pannotation.Column}.
 * This doesn't really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ColumnValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateUnique(boolean value);

	boolean validateNullable(boolean value);

	boolean validateInsertable(boolean value);

	boolean validateUpdatable(boolean value);

	boolean validateColumnDefinition(String value);

	boolean validateTable(String value);

	boolean validateLength(int value);

	boolean validatePrecision(int value);

	boolean validateScale(int value);

	boolean validateUniqueKey(String value);

	boolean validateIndex(String value);
}
