/**
 * <copyright>
 * </copyright>
 *
 * $Id: WriterValidator.java,v 1.1 2007/07/09 12:55:19 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.extralazy.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.extralazy.Writer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WriterValidator {
	boolean validate();

	boolean validateName(String value);
}
