/**
 * <copyright>
 * </copyright>
 *
 * $Id: SimpleIDValidator.java,v 1.3 2007/08/10 16:41:10 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.hb.generator.id.validation;

import java.util.Date;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.hb.generator.id.SimpleID}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimpleIDValidator {
	boolean validate();

	boolean validateAutoID(long value);

	boolean validateGenerated(long value);

	boolean validateGeneratedDate(Date value);

	boolean validateGeneratedDate(XMLGregorianCalendar value);
}
