<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adhocPackage"
    nsURI="http://www.netxforge.com/adhoc" nsPrefix="adhoc">
  <eClassifiers xsi:type="ecore:EClass" name="org.eclipse.emf.teneo.db2m.example.Channels">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkUrl" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feedUrl" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageUrl" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itunesKeywords" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspended" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyright" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managingeditor" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webmaster" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pubdate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastbuilddate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ttl" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skiphours" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skipdays" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itunesAuthor" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itunesBlock" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itunesImage" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itunesOwner" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itunesSummary" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itunesSubtitle" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itunesExplicit" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adult" unique="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatedAt" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organisationId" unique="false"/>
  </eClassifiers>
</ecore:EPackage>
