/**
 * <copyright>
 * </copyright>
 *
 * $Id: RentalBicycleValidator.java,v 1.2 2007/03/29 22:13:50 mtaal Exp $
 */
package org.eclipse.emf.teneo.rental.validation;

import org.eclipse.emf.teneo.rental.Manufacturer;
import org.eclipse.emf.teneo.rental.RentalBicycleType;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.rental.RentalBicycle}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RentalBicycleValidator {
	boolean validate();

	boolean validateType(RentalBicycleType value);

	boolean validateManufacturer(Manufacturer value);
}
