/**
 * <copyright>
 * </copyright>
 *
 * $Id: SimpleIDValidator.java,v 1.2 2007/07/11 17:34:54 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.hb.generator.id.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.hb.generator.id.SimpleID}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimpleIDValidator {
	boolean validate();

	boolean validateAutoID(long value);

	boolean validateGenerated(long value);
}
