/**
 * <copyright>
 * </copyright>
 *
 * $Id: TransactionValidator.java,v 1.1 2009/12/04 15:06:53 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.nocollectionowner.validation;

import java.util.Date;

import org.eclipse.emf.teneo.samples.issues.nocollectionowner.Order;
import org.eclipse.emf.teneo.samples.issues.nocollectionowner.Product;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.nocollectionowner.Transaction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransactionValidator {
	boolean validate();

	boolean validateNumber(String value);
	boolean validateOrder(Order value);
	boolean validateProduct(Product value);
	boolean validateStartDate(Date value);
	boolean validateEndDate(Date value);
	boolean validatePrice(double value);
	boolean validatePaidDate(Date value);
}
