/**
 * <copyright>
 * </copyright>
 *
 * $Id: MemberValidator.java,v 1.1 2007/02/08 23:09:23 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.forum.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.sample.forum.Post;
import org.eclipse.emf.teneo.samples.emf.sample.forum.Topic;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.forum.Member}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MemberValidator {
	boolean validate();

	boolean validateNickname(String value);
	boolean validatePosts(EList<Post> value);
	boolean validateCreated(EList<Topic> value);
}
