/**
 * <copyright>
 * </copyright>
 *
 * $Id: SimpleTypeObjectValidator.java,v 1.1 2007/02/08 23:09:27 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.simpletypes.validation;

import java.util.Date;

import org.eclipse.emf.teneo.samples.emf.schemaconstructs.simpletypes.SimpleEnum;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.simpletypes.SimpleTypeObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimpleTypeObjectValidator {
	boolean validate();

	boolean validateCode(String value);
	boolean validateBoo(Boolean value);
	boolean validateByt(Byte value);
	boolean validateDoubl(Double value);
	boolean validateFloat(Float value);
	boolean validateInte(Integer value);
	boolean validateLon(Long value);
	boolean validateShor(Short value);
	boolean validateEnu(SimpleEnum value);
	boolean validateDat(Date value);
}
