/**
 * <copyright>
 * </copyright>
 *
 * $Id: AValidator.java,v 1.1 2007/02/08 23:09:28 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.nestedgroup.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.eclipse.emf.teneo.samples.emf.schemaconstructs.nestedgroup.CType;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.nestedgroup.A}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateGroup(FeatureMap value);
	boolean validateB(EList<String> value);
	boolean validateC(EList<CType> value);
}
