/**
 * <copyright>
 * </copyright>
 *
 * $Id: CTypeValidator.java,v 1.1 2007/02/08 23:09:28 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.nestedgroup.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.nestedgroup.CType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CTypeValidator {
	boolean validate();

	boolean validateCname(String value);
	boolean validateCvalue(double value);
}
