/**
 * <copyright>
 * </copyright>
 *
 * $Id: NamedNativeQueryValidator.java,v 1.1 2009/07/23 11:16:29 mtaal Exp $
 */
package org.eclipse.emf.teneo.jpa.orm.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.jpa.orm.QueryHint;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.jpa.orm.NamedNativeQuery}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NamedNativeQueryValidator {
	boolean validate();

	boolean validateQuery(String value);
	boolean validateHint(EList<QueryHint> value);
	boolean validateName(String value);
	boolean validateResultClass(String value);
	boolean validateResultSetMapping(String value);
}
