<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testinheritance"
    nsURI="http://xsd.tns.example.com/testinheritance/model" nsPrefix="testinheritance">
  <eClassifiers xsi:type="ecore:EClass" name="SomeResource" eSuperTypes="#//SomeBaseClass #//SomeOtherBaseClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="SomeBaseClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anotherProperty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SomeOtherBaseClass">
    <eAnnotations source="teneo.jpa">
      <details key="value" value="@MappedSuperclass"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameValuePairs" upperBound="-1"
        eType="#//NameValuePair"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameValuePair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParentOne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anotherProperty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParentTwo">
    <eAnnotations source="teneo.jpa">
      <details key="appinfo" value="@MappedSuperclass"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Id"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="someReference" lowerBound="1"
        eType="#//SomeReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParentZero">
    <eAnnotations source="teneo.jpa">
      <details key="appinfo" value="@MappedSuperclass"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child" eSuperTypes="#//ParentZero #//ParentTwo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child2" eSuperTypes="#//ParentZero #//ParentOne #//ParentTwo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SomeReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="teneo.jpa">
        <details key="appinfo" value="@Id"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
