/**
 * <copyright>
 * </copyright>
 *
 * $Id: AddressGroupValidator.java,v 1.1 2007/02/08 23:09:26 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.groupall.validation;

import org.eclipse.emf.teneo.samples.emf.schemaconstructs.groupall.Address;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.groupall.AddressGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AddressGroupValidator {
	boolean validate();

	boolean validateGroupName(String value);
	boolean validateShipTo(Address value);
	boolean validateBillTo(Address value);
	boolean validateSimpleAddress(String value);
}
