/**
 * <copyright>
 * </copyright>
 *
 * $Id: AccessControlValidator.java,v 1.1 2007/03/28 13:56:52 mtaal Exp $
 */
package lobj.validation;

import java.util.Date;

import lobj.Sharednotes;
import lobj.User;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lobj.AccessControl}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AccessControlValidator {
	boolean validate();

	boolean validateOwner(User value);
	boolean validateLastModified(Date value);
	boolean validateLastModifiedBy(User value);
	boolean validateStatus(String value);
	boolean validateLastStatusChange(Date value);
	boolean validateLastStatusChangeBy(User value);
	boolean validateSharednotes(Sharednotes value);
	boolean validateAuthorizes(EList value);
	boolean validateEditionHistory(EList value);
	boolean validateGlobalAccess(boolean value);
	boolean validateId(String value);
}
