/**
 * <copyright>
 * </copyright>
 *
 * $Id: AddressValidator.java,v 1.1 2007/03/28 13:56:52 mtaal Exp $
 */
package lobj.validation;


/**
 * A sample validator interface for {@link lobj.Address}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AddressValidator {
	boolean validate();

	boolean validateStreet(String value);
	boolean validatePostcode(String value);
	boolean validateCity(String value);
	boolean validateState(String value);
	boolean validateCountry(String value);
	boolean validatePhone(String value);
	boolean validateFax(String value);
	boolean validateEmail(String value);
	boolean validateOtheraddr(String value);
	boolean validateId(String value);
}
