/**
 * <copyright>
 * </copyright>
 *
 * $Id: LuNodeValidator.java,v 1.1 2007/03/28 13:56:51 mtaal Exp $
 */
package lobj.validation;

import lobj.LearningUnit;

/**
 * A sample validator interface for {@link lobj.LuNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LuNodeValidator {
	boolean validate();

	boolean validateLearningUnit(LearningUnit value);
}
