/**
 * <copyright>
 * </copyright>
 *
 * $Id: NodeValidator.java,v 1.1 2007/03/28 13:56:51 mtaal Exp $
 */
package lobj.validation;


/**
 * A sample validator interface for {@link lobj.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateVisible(boolean value);
	boolean validateId(String value);
}
