/**
 * <copyright>
 * </copyright>
 *
 * $Id: PersonValidator.java,v 1.1 2007/03/28 13:56:51 mtaal Exp $
 */
package lobj.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lobj.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateHonorific(String value);
	boolean validateFirstname(String value);
	boolean validateSurname(String value);
	boolean validateContrib(String value);
	boolean validateAffiliations(EList value);
	boolean validatePersonblurb(String value);
	boolean validateId(String value);
}
