/**
 * <copyright>
 * </copyright>
 *
 * $Id: PublishInfoValidator.java,v 1.1 2007/03/28 13:56:50 mtaal Exp $
 */
package lobj.validation;

import java.util.Date;

import lobj.Publisher;

/**
 * A sample validator interface for {@link lobj.PublishInfo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PublishInfoValidator {
	boolean validate();

	boolean validateEdition(String value);
	boolean validatePubdate(Date value);
	boolean validatePublisher(Publisher value);
	boolean validatePubsnumber(String value);
	boolean validateReleaseinfo(String value);
	boolean validateId(String value);
}
