/**
 * <copyright>
 * </copyright>
 *
 * $Id: SimpleDidacMetaValidator.java,v 1.1 2007/03/28 13:56:50 mtaal Exp $
 */
package lobj.validation;

import lobj.Language;

/**
 * A sample validator interface for {@link lobj.SimpleDidacMeta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimpleDidacMetaValidator {
	boolean validate();

	boolean validateLanguage(Language value);
	boolean validateTitle(String value);
	boolean validateDescription(String value);
	boolean validateKeywords(String value);
	boolean validateId(String value);
}
