/**
 * <copyright>
 * </copyright>
 *
 * $Id: SourceValidator.java,v 1.1 2007/03/28 13:56:51 mtaal Exp $
 */
package lobj.validation;

import lobj.Author;

/**
 * A sample validator interface for {@link lobj.Source}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SourceValidator {
	boolean validate();

	boolean validateAuthor(Author value);
	boolean validateTitle(String value);
	boolean validateSubtitle(String value);
	boolean validatePublishedIn(String value);
	boolean validatePublishedBy(String value);
	boolean validatePublishDate(Object value);
	boolean validatePp(String value);
	boolean validateId(String value);
}
