/**
 * <copyright>
 * </copyright>
 *
 * $Id: UserValidator.java,v 1.1 2007/03/28 13:56:50 mtaal Exp $
 */
package lobj.validation;

import java.math.BigInteger;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lobj.User}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UserValidator {
	boolean validate();

	boolean validateLoginname(String value);
	boolean validatePassword(String value);
	boolean validateFirstname(String value);
	boolean validateLastname(String value);
	boolean validateMatriculationnr(String value);
	boolean validateScn(String value);
	boolean validateIcqnumber(String value);
	boolean validateIcqpassword(String value);
	boolean validateEntryasxml(String value);
	boolean validateLanguagenr(String value);
	boolean validateNotificationprofileasxml(String value);
	boolean validateDossierasxml(String value);
	boolean validatePhoto(byte[] value);
	boolean validateOnlinestatus(String value);
	boolean validateOnlinedate(Date value);
	boolean validateDatafilter(String value);
	boolean validateInchatsince(Date value);
	boolean validateContchatdate(Date value);
	boolean validateChatroomnr(BigInteger value);
	boolean validateFromext(BigInteger value);
	boolean validateLastlogindate(Date value);
	boolean validateCurrlogindate(Date value);
	boolean validateLastcoursematerialnr(BigInteger value);
	boolean validateLastcoursematerialviewnr(BigInteger value);
	boolean validateAuthenticateldap(BigInteger value);
	boolean validatePhotochanged(BigInteger value);
	boolean validateAuthorizations(EList value);
	boolean validateId(String value);
}
