/**
 * <copyright>
 * </copyright>
 *
 * $Id: PersonValidator.java,v 1.2 2007/07/17 17:37:32 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.joincolumns.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.teneo.samples.emf.annotations.joincolumns.Person;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.joincolumns.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateFirstName(String value);
	boolean validateLastName(String value);

	boolean validateFriends(EList<Person> value);

	boolean validateOppositeFriends(EList<Person> value);
}
