/**
 * <copyright>
 * </copyright>
 *
 * $Id: Sub1Validator.java,v 1.1 2009/10/14 22:19:41 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.bz292151.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.bz292151.Sub1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Sub1Validator {
	boolean validate();

	boolean validateA1(String value);
}
