/**
 * <copyright>
 * </copyright>
 *
 * $Id: Sub2Validator.java,v 1.2 2009/10/16 09:32:29 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.bz292151.validation;

import org.eclipse.emf.teneo.samples.issues.bz292151.Sub1;
import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.bz292151.Sub2}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Sub2Validator {
	boolean validate();

	boolean validateA1(Sub1 value);

	boolean validateA1(EObject value);
}
