<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="library" nsURI="http://www.eclipse.org/emf/teneo/samples/emf/sample/Library" nsPrefix="library">
    <eClassifiers xsi:type="ecore:EClass" name="Book">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Book"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" unique="false" lowerBound="1" eType="/1/String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="title"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pages" unique="false" lowerBound="1" eType="/1/Int" unsettable="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="pages"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" unique="false" lowerBound="1" eType="/0/BookCategory" defaultValueLiteral="Mystery" unsettable="true">
        <eAnnotations source="teneo.jpa">
          <details key="appinfo" value="@Enumerated(ORDINAL)"/>
        </eAnnotations>
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="category"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1" eType="/0/Writer" eOpposite="/0/Writer/books">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="author"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BookCategory">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="BookCategory"/>
      </eAnnotations>
      <eLiterals name="Mystery"/>
      <eLiterals name="ScienceFiction" value="1"/>
      <eLiterals name="Biography" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="BookCategoryObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="BookCategory:Object"/>
        <details key="baseType" value="BookCategory"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Library">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Library"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1" eType="/1/String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="name"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="writers" upperBound="-1" eType="/0/Writer" containment="true" resolveProxies="false">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="writers"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1" eType="/0/Book" containment="true" resolveProxies="false">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="books"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Writer">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Writer"/>
        <details key="kind" value="elementOnly"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1" eType="/1/String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="name"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="books" upperBound="-1" eType="/0/Book" eOpposite="/0/Book/author">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="books"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="type" nsURI="http://www.eclipse.org/emf/2003/XMLType" nsPrefix="xml.type">
    <eClassifiers xsi:type="ecore:EClass" name="AnyType" instanceClassName="org.eclipse.emf.ecore.xml.type.AnyType">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="anyType"/>
        <details key="kind" value="mixed"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1" eType="/2/EFeatureMapEntry">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="elementWildcard"/>
          <details key="name" value=":mixed"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="any" unique="false" upperBound="-1" eType="/2/EFeatureMapEntry" volatile="true" transient="true" derived="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="elementWildcard"/>
          <details key="wildcards" value="##any"/>
          <details key="name" value=":1"/>
          <details key="processing" value="lax"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false" upperBound="-1" eType="/2/EFeatureMapEntry">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="attributeWildcard"/>
          <details key="wildcards" value="##any"/>
          <details key="name" value=":2"/>
          <details key="processing" value="lax"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleAnyType" instanceClassName="org.eclipse.emf.ecore.xml.type.SimpleAnyType" eSuperTypes="/1/AnyType">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="simpleAnyType"/>
        <details key="kind" value="simple"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rawValue" unique="false" eType="/1/String" volatile="true" transient="true" derived="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value=":3"/>
          <details key="kind" value="simple"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="/1/AnySimpleType" volatile="true" transient="true" derived="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value=":4"/>
          <details key="kind" value="simple"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instanceType" lowerBound="1" eType="/2/EDataType" resolveProxies="false">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value=":5"/>
          <details key="kind" value="simple"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMLTypeDocumentRoot" instanceClassName="org.eclipse.emf.ecore.xml.type.XMLTypeDocumentRoot">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value=""/>
        <details key="kind" value="mixed"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false" upperBound="-1" eType="/2/EFeatureMapEntry">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="elementWildcard"/>
          <details key="name" value=":mixed"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1" eType="/2/EStringToStringMapEntry" transient="true" containment="true" resolveProxies="false">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="attribute"/>
          <details key="name" value="xmlns:prefix"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation" upperBound="-1" eType="/2/EStringToStringMapEntry" transient="true" containment="true" resolveProxies="false">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="attribute"/>
          <details key="name" value="xsi:schemaLocation"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cDATA" unique="false" upperBound="-2" eType="/1/String" volatile="true" transient="true" derived="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="cDATA"/>
          <details key="namespace" value="##targetNamespace"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" unique="false" upperBound="-2" eType="/1/String" volatile="true" transient="true" derived="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="comment"/>
          <details key="namespace" value="##targetNamespace"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-2" eType="/1/String" volatile="true" transient="true" derived="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="kind" value="element"/>
          <details key="name" value="text"/>
          <details key="namespace" value="##targetNamespace"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="AnySimpleType" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="anySimpleType"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="AnyURI" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="anyURI"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Base64Binary" instanceClassName="byte[]">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="base64Binary"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="boolean">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="boolean"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="BooleanObject" instanceClassName="java.lang.Boolean">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="boolean:Object"/>
        <details key="baseType" value="boolean"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Byte" instanceClassName="byte">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="byte"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ByteObject" instanceClassName="java.lang.Byte">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="byte:Object"/>
        <details key="baseType" value="byte"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Date" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="date"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="DateTime" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="dateTime"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Decimal" instanceClassName="java.math.BigDecimal">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="decimal"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="double">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="double"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="DoubleObject" instanceClassName="java.lang.Double">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="double:Object"/>
        <details key="baseType" value="double"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Duration" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="duration"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ENTITIES" instanceClassName="java.util.List">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="ENTITIES"/>
        <details key="baseType" value="ENTITIES_._base"/>
        <details key="minLength" value="1"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ENTITIESBase" instanceClassName="java.util.List">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="ENTITIES_._base"/>
        <details key="itemType" value="ENTITY"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ENTITY" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="ENTITY"/>
        <details key="baseType" value="NCName"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Float" instanceClassName="float">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="float"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="FloatObject" instanceClassName="java.lang.Float">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="float:Object"/>
        <details key="baseType" value="float"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="GDay" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="gDay"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="GMonth" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="gMonth"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="GMonthDay" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="gMonthDay"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="GYear" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="gYear"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="GYearMonth" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="gYearMonth"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="HexBinary" instanceClassName="byte[]">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="hexBinary"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ID" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="ID"/>
        <details key="baseType" value="NCName"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="IDREF" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="IDREF"/>
        <details key="baseType" value="NCName"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="IDREFS" instanceClassName="java.util.List">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="IDREFS"/>
        <details key="baseType" value="IDREFS_._base"/>
        <details key="minLength" value="1"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="IDREFSBase" instanceClassName="java.util.List">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="IDREFS_._base"/>
        <details key="itemType" value="IDREF"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Int" instanceClassName="int">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="int"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.math.BigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="integer"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="IntObject" instanceClassName="java.lang.Integer">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="int:Object"/>
        <details key="baseType" value="int"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Language" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="language"/>
        <details key="baseType" value="token"/>
        <details key="pattern" value="[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Long" instanceClassName="long">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="long"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="LongObject" instanceClassName="java.lang.Long">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="long:Object"/>
        <details key="baseType" value="long"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Name" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Name"/>
        <details key="baseType" value="token"/>
        <details key="pattern" value="\i\c*"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NCName" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="NCName"/>
        <details key="baseType" value="Name"/>
        <details key="pattern" value="[\i-[:]][\c-[:]]*"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NegativeInteger" instanceClassName="java.math.BigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="negativeInteger"/>
        <details key="baseType" value="nonPositiveInteger"/>
        <details key="maxInclusive" value="-1"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NMTOKEN" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="NMTOKEN"/>
        <details key="baseType" value="token"/>
        <details key="pattern" value="\c+"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NMTOKENS" instanceClassName="java.util.List">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="NMTOKENS"/>
        <details key="baseType" value="NMTOKENS_._base"/>
        <details key="minLength" value="1"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NMTOKENSBase" instanceClassName="java.util.List">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="NMTOKENS_._base"/>
        <details key="itemType" value="NMTOKEN"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NonNegativeInteger" instanceClassName="java.math.BigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="nonNegativeInteger"/>
        <details key="baseType" value="integer"/>
        <details key="minInclusive" value="0"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NonPositiveInteger" instanceClassName="java.math.BigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="nonPositiveInteger"/>
        <details key="baseType" value="integer"/>
        <details key="maxInclusive" value="0"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NormalizedString" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="normalizedString"/>
        <details key="baseType" value="string"/>
        <details key="whiteSpace" value="replace"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="NOTATION" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="NOTATION"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="PositiveInteger" instanceClassName="java.math.BigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="positiveInteger"/>
        <details key="baseType" value="nonNegativeInteger"/>
        <details key="minInclusive" value="1"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="QName" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="QName"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Short" instanceClassName="short">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="short"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ShortObject" instanceClassName="java.lang.Short">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="short:Object"/>
        <details key="baseType" value="short"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="string"/>
        <details key="whiteSpace" value="preserve"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Time" instanceClassName="java.lang.Object">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="time"/>
        <details key="baseType" value="anySimpleType"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Token" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="token"/>
        <details key="baseType" value="normalizedString"/>
        <details key="whiteSpace" value="collapse"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedByte" instanceClassName="short">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="unsignedByte"/>
        <details key="maxInclusive" value="255"/>
        <details key="minInclusive" value="0"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedByteObject" instanceClassName="java.lang.Short">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="unsignedByte:Object"/>
        <details key="baseType" value="unsignedByte"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedInt" instanceClassName="long">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="unsignedInt"/>
        <details key="maxInclusive" value="4294967295"/>
        <details key="minInclusive" value="0"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedIntObject" instanceClassName="java.lang.Long">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="unsignedInt:Object"/>
        <details key="baseType" value="unsignedInt"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedLong" instanceClassName="java.math.BigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="unsignedLong"/>
        <details key="baseType" value="nonNegativeInteger"/>
        <details key="maxInclusive" value="18446744073709551615"/>
        <details key="minInclusive" value="0"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedShort" instanceClassName="int">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="unsignedShort"/>
        <details key="maxInclusive" value="65535"/>
        <details key="minInclusive" value="0"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="UnsignedShortObject" instanceClassName="java.lang.Integer">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="unsignedShort:Object"/>
        <details key="baseType" value="unsignedShort"/>
      </eAnnotations>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" nsPrefix="ecore">
    <eClassifiers xsi:type="ecore:EClass" name="EAttribute" instanceClassName="org.eclipse.emf.ecore.EAttribute">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributeType" lowerBound="1" eType="/2/EDataType" changeable="false" volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAnnotation" instanceClassName="org.eclipse.emf.ecore.EAnnotation" eSuperTypes="/2/EModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1" eType="/2/EStringToStringMapEntry" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eModelElement" eType="/2/EModelElement" transient="true" resolveProxies="false" eOpposite="/2/EModelElement/eAnnotations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1" eType="/2/EObject" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1" eType="/2/EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EClass" instanceClassName="org.eclipse.emf.ecore.EClass">
      <eOperations name="isSuperTypeOf" eType="/2/EBoolean">
        <eParameters name="someClass" eType="/2/EClass"/>
      </eOperations>
      <eOperations name="getFeatureCount" eType="/2/EInt"/>
      <eOperations name="getEStructuralFeature" eType="/2/EStructuralFeature">
        <eParameters name="featureID" eType="/2/EInt"/>
      </eOperations>
      <eOperations name="getFeatureID" eType="/2/EInt">
        <eParameters name="feature" eType="/2/EStructuralFeature"/>
      </eOperations>
      <eOperations name="getEStructuralFeature" eType="/2/EStructuralFeature">
        <eParameters name="featureName" eType="/2/EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eSuperTypes" upperBound="-1" eType="/2/EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eOperations" upperBound="-1" eType="/2/EOperation" containment="true" resolveProxies="false" eOpposite="/2/EOperation/eContainingClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAllAttributes" upperBound="-1" eType="/2/EAttribute" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAllReferences" upperBound="-1" eType="/2/EReference" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eReferences" upperBound="-1" eType="/2/EReference" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAttributes" upperBound="-1" eType="/2/EAttribute" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAllContainments" upperBound="-1" eType="/2/EReference" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAllOperations" upperBound="-1" eType="/2/EOperation" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAllStructuralFeatures" upperBound="-1" eType="/2/EStructuralFeature" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAllSuperTypes" upperBound="-1" eType="/2/EClass" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eIDAttribute" eType="/2/EAttribute" changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eStructuralFeatures" upperBound="-1" eType="/2/EStructuralFeature" containment="true" resolveProxies="false" eOpposite="/2/EStructuralFeature/eContainingClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EClassifier" instanceClassName="org.eclipse.emf.ecore.EClassifier" abstract="true">
      <eOperations name="isInstance" eType="/2/EBoolean">
        <eParameters name="object" eType="/2/EJavaObject"/>
      </eOperations>
      <eOperations name="getClassifierID" eType="/2/EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClassName" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceClass" eType="/2/EJavaClass" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="/2/EJavaObject" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="/2/EPackage" changeable="false" transient="true" eOpposite="/2/EPackage/eClassifiers"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EDataType" instanceClassName="org.eclipse.emf.ecore.EDataType" eSuperTypes="/2/EClassifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serializable" eType="/2/EBoolean" defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EEnum" instanceClassName="org.eclipse.emf.ecore.EEnum" eSuperTypes="/2/EDataType">
      <eOperations name="getEEnumLiteral" eType="/2/EEnumLiteral">
        <eParameters name="name" eType="/2/EString"/>
      </eOperations>
      <eOperations name="getEEnumLiteral" eType="/2/EEnumLiteral">
        <eParameters name="value" eType="/2/EInt"/>
      </eOperations>
      <eOperations name="getEEnumLiteralByLiteral" eType="/2/EEnumLiteral">
        <eParameters name="literal" eType="/2/EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eLiterals" upperBound="-1" eType="/2/EEnumLiteral" containment="true" resolveProxies="false" eOpposite="/2/EEnumLiteral/eEnum"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EEnumLiteral" instanceClassName="org.eclipse.emf.ecore.EEnumLiteral" eSuperTypes="/2/ENamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="/2/EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instance" eType="/2/EEnumerator" transient="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eEnum" eType="/2/EEnum" changeable="false" transient="true" resolveProxies="false" eOpposite="/2/EEnum/eLiterals"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EFactory" instanceClassName="org.eclipse.emf.ecore.EFactory">
      <eOperations name="create" eType="/2/EObject">
        <eParameters name="eClass" eType="/2/EClass"/>
      </eOperations>
      <eOperations name="createFromString" eType="/2/EJavaObject">
        <eParameters name="eDataType" eType="/2/EDataType"/>
        <eParameters name="literalValue" eType="/2/EString"/>
      </eOperations>
      <eOperations name="convertToString" eType="/2/EString">
        <eParameters name="eDataType" eType="/2/EDataType"/>
        <eParameters name="instanceValue" eType="/2/EJavaObject"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" lowerBound="1" eType="/2/EPackage" transient="true" resolveProxies="false" eOpposite="/2/EPackage/eFactoryInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EModelElement" instanceClassName="org.eclipse.emf.ecore.EModelElement" abstract="true" eSuperTypes="/2/EObject">
      <eOperations name="getEAnnotation" eType="/2/EAnnotation">
        <eParameters name="source" eType="/2/EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eAnnotations" upperBound="-1" eType="/2/EAnnotation" containment="true" resolveProxies="false" eOpposite="/2/EAnnotation/eModelElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ENamedElement" instanceClassName="org.eclipse.emf.ecore.ENamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EObject" instanceClassName="org.eclipse.emf.ecore.EObject">
      <eOperations name="eClass" eType="/2/EClass"/>
      <eOperations name="eIsProxy" eType="/2/EBoolean"/>
      <eOperations name="eResource" eType="/2/EResource"/>
      <eOperations name="eContainer" eType="/2/EObject"/>
      <eOperations name="eContainingFeature" eType="/2/EStructuralFeature"/>
      <eOperations name="eContainmentFeature" eType="/2/EReference"/>
      <eOperations name="eContents" eType="/2/EEList"/>
      <eOperations name="eAllContents" eType="/2/ETreeIterator"/>
      <eOperations name="eCrossReferences" eType="/2/EEList"/>
      <eOperations name="eGet" eType="/2/EJavaObject">
        <eParameters name="feature" eType="/2/EStructuralFeature"/>
      </eOperations>
      <eOperations name="eGet" eType="/2/EJavaObject">
        <eParameters name="feature" eType="/2/EStructuralFeature"/>
        <eParameters name="resolve" eType="/2/EBoolean"/>
      </eOperations>
      <eOperations name="eSet">
        <eParameters name="feature" eType="/2/EStructuralFeature"/>
        <eParameters name="newValue" eType="/2/EJavaObject"/>
      </eOperations>
      <eOperations name="eIsSet" eType="/2/EBoolean">
        <eParameters name="feature" eType="/2/EStructuralFeature"/>
      </eOperations>
      <eOperations name="eUnset">
        <eParameters name="feature" eType="/2/EStructuralFeature"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EOperation" instanceClassName="org.eclipse.emf.ecore.EOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="eContainingClass" eType="/2/EClass" changeable="false" transient="true" resolveProxies="false" eOpposite="/2/EClass/eOperations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eParameters" upperBound="-1" eType="/2/EParameter" containment="true" resolveProxies="false" eOpposite="/2/EParameter/eOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eExceptions" upperBound="-1" eType="/2/EClassifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EPackage" instanceClassName="org.eclipse.emf.ecore.EPackage">
      <eOperations name="getEClassifier" eType="/2/EClassifier">
        <eParameters name="name" eType="/2/EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsURI" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nsPrefix" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eFactoryInstance" lowerBound="1" eType="/2/EFactory" transient="true" resolveProxies="false" eOpposite="/2/EFactory/ePackage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifiers" upperBound="-1" eType="/2/EClassifier" containment="true" eOpposite="/2/EClassifier/ePackage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eSubpackages" upperBound="-1" eType="/2/EPackage" containment="true" eOpposite="/2/EPackage/eSuperPackage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eSuperPackage" eType="/2/EPackage" changeable="false" transient="true" eOpposite="/2/EPackage/eSubpackages"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EParameter" instanceClassName="org.eclipse.emf.ecore.EParameter" eSuperTypes="/2/ETypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="eOperation" eType="/2/EOperation" changeable="false" transient="true" resolveProxies="false" eOpposite="/2/EOperation/eParameters"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EReference" instanceClassName="org.eclipse.emf.ecore.EReference" eSuperTypes="/2/EStructuralFeature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="container" eType="/2/EBoolean" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolveProxies" eType="/2/EBoolean" defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eOpposite" eType="/2/EReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eReferenceType" lowerBound="1" eType="/2/EClass" changeable="false" volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeature" instanceClassName="org.eclipse.emf.ecore.EStructuralFeature" abstract="true">
      <eOperations name="getFeatureID" eType="/2/EInt"/>
      <eOperations name="getContainerClass" eType="/2/EJavaClass"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeable" eType="/2/EBoolean" defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volatile" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueLiteral" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="/2/EJavaObject" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unsettable" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="/2/EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eContainingClass" eType="/2/EClass" changeable="false" transient="true" resolveProxies="false" eOpposite="/2/EClass/eStructuralFeatures"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ETypedElement" instanceClassName="org.eclipse.emf.ecore.ETypedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="/2/EBoolean" defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="/2/EBoolean" defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="/2/EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="/2/EInt" defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="/2/EBoolean" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="/2/EBoolean" changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" eType="/2/EClassifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EStringToStringMapEntry" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="/2/EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="/2/EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EBigDecimal" instanceClassName="java.math.BigDecimal">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#decimal"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EBigInteger" instanceClassName="java.math.BigInteger">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#integer"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EBoolean" instanceClassName="boolean">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#boolean"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EBooleanObject" instanceClassName="java.lang.Boolean">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="EBoolean"/>
        <details key="name" value="EBoolean:Object"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EByte" instanceClassName="byte">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#byte"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EByteArray" instanceClassName="byte[]">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#hexBinary"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EByteObject" instanceClassName="java.lang.Byte">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="EByte"/>
        <details key="name" value="EByte:Object"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EChar" instanceClassName="char"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ECharacterObject" instanceClassName="java.lang.Character">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="EChar"/>
        <details key="name" value="EChar:Object"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EDate" instanceClassName="java.util.Date"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EDiagnosticChain" instanceClassName="org.eclipse.emf.common.util.DiagnosticChain" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EDouble" instanceClassName="double">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#double"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EDoubleObject" instanceClassName="java.lang.Double">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="EDouble"/>
        <details key="name" value="EDouble:Object"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EEList" instanceClassName="org.eclipse.emf.common.util.EList" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EEnumerator" instanceClassName="org.eclipse.emf.common.util.Enumerator" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EFeatureMap" instanceClassName="org.eclipse.emf.ecore.util.FeatureMap" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EFeatureMapEntry" instanceClassName="org.eclipse.emf.ecore.util.FeatureMap$Entry"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EFloat" instanceClassName="float">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#float"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EFloatObject" instanceClassName="java.lang.Float">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="EFloat"/>
        <details key="name" value="EFloat:Object"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EInt" instanceClassName="int">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#int"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EIntegerObject" instanceClassName="java.lang.Integer">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="EInt"/>
        <details key="name" value="EInt:Object"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EJavaClass" instanceClassName="java.lang.Class"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EJavaObject" instanceClassName="java.lang.Object" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ELong" instanceClassName="long">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#long"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ELongObject" instanceClassName="java.lang.Long">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="ELong"/>
        <details key="name" value="ELong:Object"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EMap" instanceClassName="java.util.Map" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EResource" instanceClassName="org.eclipse.emf.ecore.resource.Resource" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet" serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="EShort" instanceClassName="short">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#short"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EShortObject" instanceClassName="java.lang.Short">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="EShort"/>
        <details key="name" value="EShort:Object"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EString" instanceClassName="java.lang.String">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="http://www.w3.org/2001/XMLSchema#string"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ETreeIterator" instanceClassName="org.eclipse.emf.common.util.TreeIterator" serializable="false"/>
  </ecore:EPackage>
</xmi:XMI>
