/**
 * <copyright>
 * </copyright>
 *
 * $Id: FooValidator.java,v 1.1 2009/10/02 07:47:37 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.bz290969.validation;

import org.eclipse.emf.teneo.samples.issues.bz290969.BarKey;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.bz290969.Foo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FooValidator {
	boolean validate();

	boolean validateBarKey(BarKey value);
}
