/**
 * <copyright>
 * </copyright>
 *
 * $Id: OrderValidator.java,v 1.1 2009/12/04 15:06:53 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.nocollectionowner.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.issues.nocollectionowner.Customer;
import org.eclipse.emf.teneo.samples.issues.nocollectionowner.Transaction;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.nocollectionowner.Order}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrderValidator {
	boolean validate();

	boolean validateNumber(String value);
	boolean validateTransactions(EList<Transaction> value);
	boolean validateCustomer(Customer value);
	boolean validateComments(EList<String> value);
}
