/**
 * <copyright>
 * </copyright>
 *
 * $Id: ProductCategoryValidator.java,v 1.1 2009/12/04 15:06:53 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.nocollectionowner.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.issues.nocollectionowner.Product;
import org.eclipse.emf.teneo.samples.issues.nocollectionowner.ProductCategory;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.nocollectionowner.ProductCategory}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductCategoryValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateProducts(EList<Product> value);
	boolean validateSubCategorys(EList<ProductCategory> value);
	boolean validateParent(ProductCategory value);
}
