/**
 * <copyright>
 * </copyright>
 *
 * $Id: AbstractContentValidator.java,v 1.1 2007/03/28 13:56:50 mtaal Exp $
 */
package lobj.validation;

import lobj.Language;
import lobj.Source;

/**
 * A sample validator interface for {@link lobj.AbstractContent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractContentValidator {
	boolean validate();

	boolean validateHeading(String value);
	boolean validateLanguage(Language value);
	boolean validateSource(Source value);
}
