/**
 * <copyright>
 * </copyright>
 *
 * $Id: AffiliationValidator.java,v 1.1 2007/03/28 13:56:50 mtaal Exp $
 */
package lobj.validation;

import lobj.Address;

/**
 * A sample validator interface for {@link lobj.Affiliation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AffiliationValidator {
	boolean validate();

	boolean validateShortaffil(String value);
	boolean validateJobtitle(String value);
	boolean validateOrgname(String value);
	boolean validateOrgdiv(String value);
	boolean validateAddress(Address value);
	boolean validateId(String value);
}
