/**
 * <copyright>
 * </copyright>
 *
 * $Id: BlocktypeValidator.java,v 1.1 2007/03/28 13:56:52 mtaal Exp $
 */
package lobj.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lobj.Blocktype}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlocktypeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateCreationDate(Date value);
	boolean validateStyleRef(String value);
	boolean validateDomains(EList value);
	boolean validateId(String value);
}
