/**
 * <copyright>
 * </copyright>
 *
 * $Id: BlockAudiofileValidator.java,v 1.1 2007/03/28 13:56:51 mtaal Exp $
 */
package lobj.validation;

import lobj.ResrcFiletype;

/**
 * A sample validator interface for {@link lobj.BlockAudiofile}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlockAudiofileValidator {
	boolean validate();

	boolean validateFile(byte[] value);
	boolean validateOriginalextension(String value);
	boolean validateFilesize(int value);
	boolean validateResrcHref(String value);
	boolean validateResrcFiletype(ResrcFiletype value);
}
