/**
 * <copyright>
 * </copyright>
 *
 * $Id: CourseValidator.java,v 1.1 2007/03/28 13:56:50 mtaal Exp $
 */
package lobj.validation;

import lobj.CourseMeta;
import lobj.Coursetype;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lobj.Course}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CourseValidator {
	boolean validate();

	boolean validateCourseMeta(CourseMeta value);
	boolean validateExternalMetadata(EList value);
	boolean validateCoursetype(Coursetype value);
	boolean validateOutlineAsXml(String value);
	boolean validateModule(EList value);
}
