/**
 * <copyright>
 * </copyright>
 *
 * $Id: CourseMetaValidator.java,v 1.1 2007/03/28 13:56:51 mtaal Exp $
 */
package lobj.validation;

import java.math.BigInteger;

import java.util.Date;

import lobj.Language;
import lobj.User;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lobj.CourseMeta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CourseMetaValidator {
	boolean validate();

	boolean validateDidacMeta(EList value);
	boolean validateHours(int value);
	boolean validateLvanr(String value);
	boolean validateColumnfilterasxml(String value);
	boolean validateFromext(BigInteger value);
	boolean validateCreationDate(Date value);
	boolean validateLecturer(User value);
	boolean validateDefLang(Language value);
}
