/**
 * <copyright>
 * </copyright>
 *
 * $Id: DidacMetaValidator.java,v 1.1 2007/03/28 13:56:53 mtaal Exp $
 */
package lobj.validation;

import lobj.Precognition;

/**
 * A sample validator interface for {@link lobj.DidacMeta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DidacMetaValidator {
	boolean validate();

	boolean validateGoal(String value);
	boolean validatePrecognition(Precognition value);
}
