/**
 * <copyright>
 * </copyright>
 *
 * $Id: ModuleMetaValidator.java,v 1.1 2007/03/28 13:56:51 mtaal Exp $
 */
package lobj.validation;

import java.util.Date;

import lobj.Language;
import lobj.PublishInfo;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lobj.ModuleMeta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleMetaValidator {
	boolean validate();

	boolean validateDidacMeta(EList value);
	boolean validateCreationDate(Date value);
	boolean validateAuthors(EList value);
	boolean validatePublishInfo(PublishInfo value);
	boolean validateDefLang(Language value);
}
