/**
 * <copyright>
 * </copyright>
 *
 * $Id: ResrcFiletypeValidator.java,v 1.1 2007/03/28 13:56:52 mtaal Exp $
 */
package lobj.validation;


/**
 * A sample validator interface for {@link lobj.ResrcFiletype}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResrcFiletypeValidator {
	boolean validate();

	boolean validateFiletypeExtension(String value);
	boolean validateFiletypeDesc(String value);
	boolean validateImage(boolean value);
	boolean validateApplet(boolean value);
	boolean validateFiletypeImageSmall(String value);
	boolean validateFiletypeImageBif(String value);
	boolean validateId(String value);
}
