/**
 * <copyright>
 * </copyright>
 *
 * $Id: YourItemValidator.java,v 1.1 2007/02/08 23:09:27 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.nmset.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.annotations.nmset.MyItem;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.nmset.YourItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface YourItemValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateMyItem(EList<MyItem> value);
}
