<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="teneotest"
    nsURI="http://www.eclipse.org/emf/teneo/samples/issues/bz292151" nsPrefix="bz292151">
  <eClassifiers xsi:type="ecore:EClass" name="Base"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sub1" eSuperTypes="#//Base">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sub2" eSuperTypes="#//Base">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>