<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
   xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="srd"
   nsURI="http://srd" nsPrefix="srd">
 <eClassifiers xsi:type="ecore:EClass" name="Service">
   <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
       eType="#//Link" containment="true" eOpposite="#//Link/service"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="contacts" upperBound="-1"
       eType="#//Contact" eOpposite="#//Contact/services"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
       eType="#//Note" containment="true" eOpposite="#//Note/service"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
       eType="#//Location" containment="true" eOpposite="#//Location/service"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="serviceGroup" lowerBound="1"
       eType="#//ServiceGroup" eOpposite="#//ServiceGroup/services"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="organizations" upperBound="-1"
       eType="#//Organization" eOpposite="#//Organization/services"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="longName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="EPGName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="adult" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalLaunch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="local" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="xmitProfile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="epgSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestedVideoQuality"
       eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="nocViewable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="blackedOut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="namedEquipment" upperBound="-1"
       eType="#//NamedEquipment" eOpposite="#//NamedEquipment/services"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="routerPorts" upperBound="-1"
       eType="#//RouterPort" containment="true" eOpposite="#//RouterPort/service"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="allServices" lowerBound="1"
       eType="#//AllServices" eOpposite="#//AllServices/services"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="CheyenneUplink" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="GilbertUplink" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Link">
   <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
       eType="#//Service" eOpposite="#//Service/links"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Contact">
   <eStructuralFeatures xsi:type="ecore:EReference" name="physicalAddresses" upperBound="-1"
       eType="#//PhysicalAddress" containment="true" eOpposite="#//PhysicalAddress/contact"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="phoneNumbers" upperBound="-1"
       eType="#//PhoneNumber" containment="true" eOpposite="#//PhoneNumber/contact"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="emailAddresses" upperBound="-1"
       eType="#//EmailAddress" containment="true" eOpposite="#//EmailAddress/contact"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="authInfo" upperBound="-1"
       eType="#//AuthInfo" containment="true" eOpposite="#//AuthInfo/contact"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="urlAddresses" upperBound="-1"
       eType="#//UrlAddress" containment="true" eOpposite="#//UrlAddress/contact"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="ipAddresses" upperBound="-1"
       eType="#//IpAddress" containment="true" eOpposite="#//IpAddress/contact"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
       eType="#//Service" eOpposite="#//Service/contacts"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="namedEquipment" upperBound="-1"
       eType="#//NamedEquipment" eOpposite="#//NamedEquipment/contacts"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="organizations" lowerBound="1"
       eType="#//Organization" eOpposite="#//Organization/contacts"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="MiddleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="NickName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="CallOrder" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Note">
   <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
       eType="#//Service" eOpposite="#//Service/notes"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="namedEquipment" lowerBound="1"
       eType="#//NamedEquipment" eOpposite="#//NamedEquipment/notes"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="routerPort" lowerBound="1"
       eType="#//RouterPort" eOpposite="#//RouterPort/notes"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="critical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AuthInfo">
   <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
       eType="#//Contact" eOpposite="#//Contact/authInfo"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="authKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="EmailAddress">
   <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
       eType="#//Contact" eOpposite="#//Contact/emailAddresses"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="IpAddress">
   <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
       eType="#//Contact" eOpposite="#//Contact/ipAddresses"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="IP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="PhoneNumber">
   <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
       eType="#//Contact" eOpposite="#//Contact/phoneNumbers"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="AreaCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="CountryCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShortNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="UrlAddress">
   <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
       eType="#//Contact" eOpposite="#//Contact/urlAddresses"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="PhysicalAddress">
   <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
       eType="#//Contact" eOpposite="#//Contact/physicalAddresses"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="City" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="SecondLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ThirdLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="FourthLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="State" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="PostalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Organization">
   <eStructuralFeatures xsi:type="ecore:EReference" name="contacts" upperBound="-1"
       eType="#//Contact" containment="true" eOpposite="#//Contact/organizations"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
       eType="#//Service" eOpposite="#//Service/organizations"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="namedEquipment" upperBound="-1"
       eType="#//NamedEquipment" eOpposite="#//NamedEquipment/organizations"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="contactList" lowerBound="1"
       eType="#//ContactList" eOpposite="#//ContactList/organizations"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Sar" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="Hpa" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="encMod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequencyBand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="misc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="hpaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="hpaUse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="UpConverter" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="attenuation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ucOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ptcNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ucType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="DtoAConverter" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="AtoDConverter" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalPhase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalPhase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Satellite" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="orbitalSlot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandID" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="SourceSatellite" eSuperTypes="#//Satellite"/>
 <eClassifiers xsi:type="ecore:EClass" name="EchostarSatellite" eSuperTypes="#//Satellite"/>
 <eClassifiers xsi:type="ecore:EClass" name="Cherrypicker" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="in1PrimarySource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="in2PrimarySource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="in3PrimarySource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="in4PrimarySource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="in5PrimarySource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="in6PrimarySource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="in7PrimarySource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="in8PrimarySource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="out1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="out2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="out3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="out4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="DishReceiver" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="channel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="downlinkFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="forwardRateCorrection"
       eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lbandFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="smartCard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dishReceiverType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitAuthorizationNumber"
       eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="CommercialInserter" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="cueSource" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="cueType" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtmfStartNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtmfStopNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="preRoll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverID" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="tcid" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="vbiDecoder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="wegenerCardID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="zone" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="TandB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AudioDeEmbedder" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group1Pr1GainDB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group1Pr1Swap" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group1Pr2GainDB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group1Pr2Swap" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group1Swap" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group2Pr1GainDB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group2Pr1Swap" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group2Pr2GainDB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group2Pr2Swap" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="group2Swap" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Antenna" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="acu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="azimuth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="deIce" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="drive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="elevation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="gain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="misc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeM" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="track" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="antennaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="antennaUse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Feed" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lnb1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lnb2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lnb3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lnb4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="feedType" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Hydra" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="engineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="head" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="module" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="MonitorWall" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ptc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="rfDesignation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="rfDisType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="EchostarXpndrFreq" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="SourceXpndrFreq" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="DividerPort" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lbandFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="BackhaulGroundStation" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="City" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="SecondLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ThirdLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="FourthLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="PostalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="State" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="DistributionAmp" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frameNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="daType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="RouterPort">
   <eStructuralFeatures xsi:type="ecore:EReference" name="router" lowerBound="1"
       eType="#//Router" eOpposite="#//Router/routerPorts"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
       eType="#//Note" containment="true" eOpposite="#//Note/routerPort"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentAlias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="portType" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkedToAlias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkedToId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
       eType="#//Service" eOpposite="#//Service/routerPorts"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="portLocations" upperBound="-1"
       eType="#//Location" eOpposite="#//Location/routerPort"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="RfPatch" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="band" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="designation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="expansion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Encoder" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioConfigStat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pr1Language" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="satellite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pr2Language" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pr3Language" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pr4Language" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AudioEmbedder" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="pr1Gain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="pr2Gain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Fiber" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="customer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="fiber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="VideoServer" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Ifl" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="endLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="startLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="otherIfls" upperBound="-1"
       eType="#//Ifl"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Ici" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ptcNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="IpSwitch" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="IpRouter" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ipAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Patch" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="patchRow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="StandardsConverter" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="Divider" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="barCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="FiberPop" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="circuitID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="City" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Country" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="SecondLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="ThirdLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="FourthLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="PostalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="State" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="DolbyEEncoder" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="DolbyEDecoder" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="Ac3Decoder" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="Ac3Encoder" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="IpHub" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="FrameSync" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="AtmSwitch" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="LocalRack" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="CellAce" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="Monitor" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="ReceiverDecoder" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr1" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr2" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr3" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr4" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="smartCard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="ReceiverMpeg2" eSuperTypes="#//ReceiverDecoder">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr1Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr2Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr3Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="band" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="bouquet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="downlinkFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="fec" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lbandFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="netID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="streamChannel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitAuthorizationNumber"
       eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="videoPid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr4Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="transponder" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="ReceiverAnalog" eSuperTypes="#//ReceiverDecoder">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="band" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="channel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="downlinkFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lbandFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitAuthorizationNumber"
       eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="transponder" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="ReceiverDigicipher" eSuperTypes="#//ReceiverDecoder">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr1Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr2Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr3Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="band" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="digicipherChannel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="digicipherVct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="downlinkFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="fec" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lbandFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="rfInputPort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitAuthorizationNumber"
       eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="videoPid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="transponder" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr4Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="ReceiverFiber" eSuperTypes="#//ReceiverDecoder">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr1Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr2Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr3Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="fec" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="streamChannel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="videoPid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputFormat" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr4Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="ReceiverTelco" eSuperTypes="#//ReceiverDecoder">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr1Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr2Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr3Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="fec" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="netID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="streamChannel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="videoPid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="ReceiverAsi" eSuperTypes="#//ReceiverDecoder">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr1Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr2Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr3Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="fec" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="netID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="streamChannel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="videoPid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioPr4Pid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="NamedEquipmentList">
   <eStructuralFeatures xsi:type="ecore:EReference" name="namedEquipment" upperBound="-1"
       eType="#//NamedEquipment" containment="true" eOpposite="#//NamedEquipment/namedEquipmentList"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="facility" lowerBound="1"
       eType="#//Facility" eOpposite="#//Facility/namedEquipmentList"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
       eType="#//Note" containment="true" eOpposite="#//Note/namedEquipment"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="contacts" upperBound="-1"
       eType="#//Contact" eOpposite="#//Contact/namedEquipment"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="namedEquipmentList" lowerBound="1"
       eType="#//NamedEquipmentList" eOpposite="#//NamedEquipmentList/namedEquipment"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="organizations" upperBound="-1"
       eType="#//Organization" eOpposite="#//Organization/namedEquipment"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="building" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="manufacturer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="rack" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="room" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="serialNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="slot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="spare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="subslot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
       eType="#//Service" eOpposite="#//Service/namedEquipment"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="equipmentLocations" upperBound="-1"
       eType="#//Location" eOpposite="#//Location/namedEquipment"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Router" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EReference" name="routerPorts" upperBound="-1"
       eType="#//RouterPort" eOpposite="#//RouterPort/router"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstPort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastInPort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastOutPort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="numInPorts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOutPorts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="routerType" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Location">
   <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
       eType="#//Service" eOpposite="#//Service/locations"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLinks" upperBound="-1"
       eType="#//Link"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLinks" upperBound="-1"
       eType="#//Link"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="routerPort" lowerBound="1"
       eType="#//RouterPort" eOpposite="#//RouterPort/portLocations"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="namedEquipment" lowerBound="1"
       eType="#//NamedEquipment" eOpposite="#//NamedEquipment/equipmentLocations"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="ContactList">
   <eStructuralFeatures xsi:type="ecore:EReference" name="echostar" lowerBound="1"
       eType="#//Echostar" eOpposite="#//Echostar/contactList"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="organizations" upperBound="-1"
       eType="#//Organization" containment="true" eOpposite="#//Organization/contactList"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Echostar">
   <eStructuralFeatures xsi:type="ecore:EReference" name="contactList" lowerBound="1"
       eType="#//ContactList" containment="true" eOpposite="#//ContactList/echostar"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="enumAttrList" lowerBound="1"
       eType="#//EnumAttrList" containment="true" eOpposite="#//EnumAttrList/echostar"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="facilities" upperBound="-1"
       eType="#//Facility" containment="true" eOpposite="#//Facility/echostar"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="ServiceGroup" eSuperTypes="#//AbstractServiceGroup">
   <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
       eType="#//Service" eOpposite="#//Service/serviceGroup"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="serviceGroup" eType="#//ServiceGroup"
       eOpposite="#//ServiceGroup/serviceGroups"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="serviceGroups" upperBound="-1"
       eType="#//ServiceGroup" containment="true" eOpposite="#//ServiceGroup/serviceGroup"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="EnumAttrList">
   <eStructuralFeatures xsi:type="ecore:EReference" name="echostar" lowerBound="1"
       eType="#//Echostar" eOpposite="#//Echostar/enumAttrList"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="enumAttrs" upperBound="-1"
       eType="#//EnumAttr" containment="true" eOpposite="#//EnumAttr/enumAttrList"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="EnumAttr">
   <eStructuralFeatures xsi:type="ecore:EReference" name="enumAttrList" lowerBound="1"
       eType="#//EnumAttrList" eOpposite="#//EnumAttrList/enumAttrs"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="enumValues" upperBound="-1"
       eType="#//EnumValue" containment="true" resolveProxies="false" eOpposite="#//EnumValue/enumAttr"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AttrOwner" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EDataType" name="EnumType" instanceClassName="java.lang.String"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrCueType" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrCueSource" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrPolarity" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrAudioPr1" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrAudioPr2" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrAudioPr3" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrBand" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrAudioPr4" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrFec" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrRouterType" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrPortType" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrLanguage" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrFeedType" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrGroup1Swap" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrGroup2Swap" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrGroup1Pr1Swap" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrGroup1Pr2Swap" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrGroup2Pr1Swap" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrGroup2Pr2Swap" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrTcid" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrServerID" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrZone" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrType" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrBandID" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrManufacturer" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="DelayServer" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="delayServerType" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputPort" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputPort" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="transportStream" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AttrDelayServerType" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrInputPort" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrOutputPort" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrTransportStream" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrTransponder" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="Facility">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="echostar" lowerBound="1"
       eType="#//Echostar" eOpposite="#//Echostar/facilities"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="namedEquipmentList" lowerBound="1"
       eType="#//NamedEquipmentList" containment="true" eOpposite="#//NamedEquipmentList/facility"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
       eType="#//AbstractServiceGroup" containment="true" eOpposite="#//AbstractServiceGroup/facility"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AttrInputFormat" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="PlayOutFacility" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="siteName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandID" eType="#//EnumType"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AbstractServiceGroup">
   <eStructuralFeatures xsi:type="ecore:EReference" name="facility" lowerBound="1"
       eType="#//Facility" eOpposite="#//Facility/groups"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AllServices" eSuperTypes="#//AbstractServiceGroup">
   <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
       eType="#//Service" containment="true" eOpposite="#//Service/allServices"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AttrPr1Language" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrPr2Language" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrPr3Language" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrPr4Language" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrTrack" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="EnumValue">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="enumAttr" lowerBound="1"
       eType="#//EnumAttr" eOpposite="#//EnumAttr/enumValues"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Generic" eSuperTypes="#//NamedEquipment"/>
 <eClassifiers xsi:type="ecore:EClass" name="DownConverter" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="attenuation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dcOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="dcType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="SpacecraftReceiver" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="recUse" eType="#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="SpacecraftTransmitter" eSuperTypes="#//NamedEquipment">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="polarity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="txUse" eType="ecore:EDataType srd.ecore#//EnumType"/>
 </eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="AttrCallOrder" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrCheyenneUplink" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrGilbertUplink" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrRecUse" eSuperTypes="#//EnumAttr"/>
 <eClassifiers xsi:type="ecore:EClass" name="AttrTxUse" eSuperTypes="#//EnumAttr"/>
</ecore:EPackage>

