<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="main"
    nsURI="http:///main.ecore" nsPrefix="main">
  <eClassifiers xsi:type="ecore:EClass" name="ChildObject2" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildObject1" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedObject" eType="#//BaseObject"
        eOpposite="#//BaseObject/object1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseObject" eSuperTypes="#//BaseComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object1" eType="#//ChildObject1"
        eOpposite="#//ChildObject1/linkedObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseGroup" eSuperTypes="#//BaseComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//BaseComponent" containment="true" eOpposite="#//BaseComponent/group"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//BaseGroup"
        transient="true" eOpposite="#//BaseGroup/components"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildObject3" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildObject4" eSuperTypes="#//BaseObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thickness" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
</ecore:EPackage>
