/**
 * <copyright>
 * </copyright>
 *
 * $Id: XMLDeviantValidator.java,v 1.1 2007/02/08 23:09:27 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.restriction.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.restriction.XMLDeviant}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XMLDeviantValidator {
	boolean validate();

	boolean validateNumPosts(BigInteger value);
	boolean validateSignature(String value);
	boolean validateEmail(String value);
	boolean validateFirstSubscribed(Object value);
	boolean validateMailReader(String value);
}
