/**
 * <copyright>
 * </copyright>
 *
 * $Id: FruitValidator.java,v 1.1 2007/07/09 12:55:19 mtaal Exp $
 */
package tc.apple.validation;

import org.eclipse.emf.common.util.EList;

import tc.tree.BigTree;

/**
 * A sample validator interface for {@link tc.apple.Fruit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FruitValidator {
	boolean validate();

	boolean validateBigtree(EList<BigTree> value);
	boolean validateUniqueName(String value);
}
