/**
 * <copyright>
 * </copyright>
 *
 * $Id: AnotherEmbeddableValidator.java,v 1.2 2009/12/04 15:06:58 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.embedded.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.teneo.samples.emf.annotations.embedded.AOneToMany;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.embedded.AnotherEmbeddable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnotherEmbeddableValidator {
	boolean validate();

	boolean validateAnotherName(String value);

	boolean validateAOneToMany(EList<AOneToMany> value);
}
