/**
 * <copyright>
 * </copyright>
 *
 * $Id: AutoIDValidator.java,v 1.1 2007/07/11 18:59:48 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.id.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.id.AutoID}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AutoIDValidator {
	boolean validate();

	boolean validateAutoID(long value);
	boolean validateName(String value);
}
