/**
 * <copyright>
 * </copyright>
 *
 * $Id: TestAValidator.java,v 1.2 2007/07/04 19:29:56 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.detach.detachtest.validation;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.teneo.samples.emf.detach.detachtest.TestB;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.detach.detachtest.TestA}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TestAValidator {
	boolean validate();

	boolean validateCode(String value);
	boolean validateTestB(EObject value);

	boolean validateTestB(TestB value);
}
