/**
 * <copyright>
 * </copyright>
 *
 * $Id: RentalContractValidator.java,v 1.1 2007/03/07 23:34:08 mtaal Exp $
 */
package org.eclipse.emf.teneo.rental.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.rental.RentalUnit;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.rental.RentalContract}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RentalContractValidator {
	boolean validate();

	boolean validateRentToBusinessPartner(String value);
	boolean validateStartDate(Date value);
	boolean validateEndDate(Date value);
	boolean validateCost(float value);
	boolean validateRentalUnits(EList<RentalUnit> value);
}
