/**
 * <copyright>
 * </copyright>
 *
 * $Id: DiscriminatorColumnValidator.java,v 1.2 2009/09/13 14:45:54 mtaal Exp $
 */
package org.eclipse.emf.teneo.annotations.pannotation.validation;

import org.eclipse.emf.teneo.annotations.pannotation.Column;
import org.eclipse.emf.teneo.annotations.pannotation.DiscriminatorType;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.annotations.pannotation.DiscriminatorColumn}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DiscriminatorColumnValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDiscriminatorType(DiscriminatorType value);
	boolean validateColumnDefinition(String value);
	boolean validateLength(int value);

	boolean validateColumn(Column value);
}
