/**
 * <copyright>
 * </copyright>
 *
 * $Id: IndexColumnValidator.java,v 1.1 2009/12/13 10:14:18 mtaal Exp $
 */
package org.eclipse.emf.teneo.annotations.pannotation.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.annotations.pannotation.IndexColumn}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IndexColumnValidator {
	boolean validate();

	boolean validateName(String value);
}
