/**
 * <copyright>
 * </copyright>
 *
 * $Id: TBookValidator.java,v 1.1 2007/07/09 14:02:31 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.hibernate.transientotm.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.hibernate.transientotm.TWriter;
import org.eclipse.emf.teneo.samples.emf.hibernate.transientotm.TBook;
import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.hibernate.transientotm.TBook}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TBookValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateAuthors(EList<EObject> value);
}
