/**
 * <copyright>
 * </copyright>
 *
 * $Id: Hbm30ItemProviderAdapterFactory.java,v 1.1 2010/08/18 09:29:32 cbouhier Exp $
 */
package org.eclipse.emf.teneo.db2m.hbm30.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.eclipse.emf.teneo.db2m.hbm30.util.Hbm30AdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Hbm30ItemProviderAdapterFactory extends Hbm30AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Hbm30ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Any} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnyItemProvider anyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Any}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnyAdapter() {
		if (anyItemProvider == null) {
			anyItemProvider = new AnyItemProvider(this);
		}

		return anyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Array} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayItemProvider arrayItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Array}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayAdapter() {
		if (arrayItemProvider == null) {
			arrayItemProvider = new ArrayItemProvider(this);
		}

		return arrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Bag} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BagItemProvider bagItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Bag}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBagAdapter() {
		if (bagItemProvider == null) {
			bagItemProvider = new BagItemProvider(this);
		}

		return bagItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Cache} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CacheItemProvider cacheItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Cache}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCacheAdapter() {
		if (cacheItemProvider == null) {
			cacheItemProvider = new CacheItemProvider(this);
		}

		return cacheItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Class} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassItemProvider classItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Class}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassAdapter() {
		if (classItemProvider == null) {
			classItemProvider = new ClassItemProvider(this);
		}

		return classItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Collection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionItemProvider collectionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Collection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionAdapter() {
		if (collectionItemProvider == null) {
			collectionItemProvider = new CollectionItemProvider(this);
		}

		return collectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.CollectionId} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionIdItemProvider collectionIdItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.CollectionId}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionIdAdapter() {
		if (collectionIdItemProvider == null) {
			collectionIdItemProvider = new CollectionIdItemProvider(this);
		}

		return collectionIdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Column} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnItemProvider columnItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Column}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnAdapter() {
		if (columnItemProvider == null) {
			columnItemProvider = new ColumnItemProvider(this);
		}

		return columnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Component} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentItemProvider componentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Component}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentAdapter() {
		if (componentItemProvider == null) {
			componentItemProvider = new ComponentItemProvider(this);
		}

		return componentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.CompositeElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeElementItemProvider compositeElementItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.CompositeElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeElementAdapter() {
		if (compositeElementItemProvider == null) {
			compositeElementItemProvider = new CompositeElementItemProvider(this);
		}

		return compositeElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.CompositeId} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeIdItemProvider compositeIdItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.CompositeId}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeIdAdapter() {
		if (compositeIdItemProvider == null) {
			compositeIdItemProvider = new CompositeIdItemProvider(this);
		}

		return compositeIdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.CompositeIndex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeIndexItemProvider compositeIndexItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.CompositeIndex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeIndexAdapter() {
		if (compositeIndexItemProvider == null) {
			compositeIndexItemProvider = new CompositeIndexItemProvider(this);
		}

		return compositeIndexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.CompositeMapKey} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeMapKeyItemProvider compositeMapKeyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.CompositeMapKey}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeMapKeyAdapter() {
		if (compositeMapKeyItemProvider == null) {
			compositeMapKeyItemProvider = new CompositeMapKeyItemProvider(this);
		}

		return compositeMapKeyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.DatabaseObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatabaseObjectItemProvider databaseObjectItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.DatabaseObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatabaseObjectAdapter() {
		if (databaseObjectItemProvider == null) {
			databaseObjectItemProvider = new DatabaseObjectItemProvider(this);
		}

		return databaseObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Definition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefinitionItemProvider definitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Definition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefinitionAdapter() {
		if (definitionItemProvider == null) {
			definitionItemProvider = new DefinitionItemProvider(this);
		}

		return definitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.DialectScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DialectScopeItemProvider dialectScopeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.DialectScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDialectScopeAdapter() {
		if (dialectScopeItemProvider == null) {
			dialectScopeItemProvider = new DialectScopeItemProvider(this);
		}

		return dialectScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Discriminator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiscriminatorItemProvider discriminatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Discriminator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiscriminatorAdapter() {
		if (discriminatorItemProvider == null) {
			discriminatorItemProvider = new DiscriminatorItemProvider(this);
		}

		return discriminatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.DynamicComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DynamicComponentItemProvider dynamicComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.DynamicComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDynamicComponentAdapter() {
		if (dynamicComponentItemProvider == null) {
			dynamicComponentItemProvider = new DynamicComponentItemProvider(this);
		}

		return dynamicComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Element} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElementItemProvider elementItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Element}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElementAdapter() {
		if (elementItemProvider == null) {
			elementItemProvider = new ElementItemProvider(this);
		}

		return elementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Filter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterItemProvider filterItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Filter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterAdapter() {
		if (filterItemProvider == null) {
			filterItemProvider = new FilterItemProvider(this);
		}

		return filterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.FilterDef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterDefItemProvider filterDefItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.FilterDef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterDefAdapter() {
		if (filterDefItemProvider == null) {
			filterDefItemProvider = new FilterDefItemProvider(this);
		}

		return filterDefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.FilterParam} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterParamItemProvider filterParamItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.FilterParam}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterParamAdapter() {
		if (filterParamItemProvider == null) {
			filterParamItemProvider = new FilterParamItemProvider(this);
		}

		return filterParamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Generator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneratorItemProvider generatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Generator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneratorAdapter() {
		if (generatorItemProvider == null) {
			generatorItemProvider = new GeneratorItemProvider(this);
		}

		return generatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.HibernateMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HibernateMappingItemProvider hibernateMappingItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.HibernateMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHibernateMappingAdapter() {
		if (hibernateMappingItemProvider == null) {
			hibernateMappingItemProvider = new HibernateMappingItemProvider(this);
		}

		return hibernateMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Id} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IdItemProvider idItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Id}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIdAdapter() {
		if (idItemProvider == null) {
			idItemProvider = new IdItemProvider(this);
		}

		return idItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Idbag} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IdbagItemProvider idbagItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Idbag}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIdbagAdapter() {
		if (idbagItemProvider == null) {
			idbagItemProvider = new IdbagItemProvider(this);
		}

		return idbagItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Import} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportItemProvider importItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportAdapter() {
		if (importItemProvider == null) {
			importItemProvider = new ImportItemProvider(this);
		}

		return importItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Index} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndexItemProvider indexItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Index}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndexAdapter() {
		if (indexItemProvider == null) {
			indexItemProvider = new IndexItemProvider(this);
		}

		return indexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.IndexManyToAny} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndexManyToAnyItemProvider indexManyToAnyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.IndexManyToAny}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndexManyToAnyAdapter() {
		if (indexManyToAnyItemProvider == null) {
			indexManyToAnyItemProvider = new IndexManyToAnyItemProvider(this);
		}

		return indexManyToAnyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.IndexManyToMany} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndexManyToManyItemProvider indexManyToManyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.IndexManyToMany}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndexManyToManyAdapter() {
		if (indexManyToManyItemProvider == null) {
			indexManyToManyItemProvider = new IndexManyToManyItemProvider(this);
		}

		return indexManyToManyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Join} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinItemProvider joinItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Join}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinAdapter() {
		if (joinItemProvider == null) {
			joinItemProvider = new JoinItemProvider(this);
		}

		return joinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.JoinedSubclass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinedSubclassItemProvider joinedSubclassItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.JoinedSubclass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinedSubclassAdapter() {
		if (joinedSubclassItemProvider == null) {
			joinedSubclassItemProvider = new JoinedSubclassItemProvider(this);
		}

		return joinedSubclassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Key} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KeyItemProvider keyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Key}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKeyAdapter() {
		if (keyItemProvider == null) {
			keyItemProvider = new KeyItemProvider(this);
		}

		return keyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.KeyManyToOne} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KeyManyToOneItemProvider keyManyToOneItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.KeyManyToOne}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKeyManyToOneAdapter() {
		if (keyManyToOneItemProvider == null) {
			keyManyToOneItemProvider = new KeyManyToOneItemProvider(this);
		}

		return keyManyToOneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.KeyProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KeyPropertyItemProvider keyPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.KeyProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKeyPropertyAdapter() {
		if (keyPropertyItemProvider == null) {
			keyPropertyItemProvider = new KeyPropertyItemProvider(this);
		}

		return keyPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.List} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListItemProvider listItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.List}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListAdapter() {
		if (listItemProvider == null) {
			listItemProvider = new ListItemProvider(this);
		}

		return listItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ListIndex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListIndexItemProvider listIndexItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ListIndex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListIndexAdapter() {
		if (listIndexItemProvider == null) {
			listIndexItemProvider = new ListIndexItemProvider(this);
		}

		return listIndexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.LoadCollection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoadCollectionItemProvider loadCollectionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.LoadCollection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoadCollectionAdapter() {
		if (loadCollectionItemProvider == null) {
			loadCollectionItemProvider = new LoadCollectionItemProvider(this);
		}

		return loadCollectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Loader} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoaderItemProvider loaderItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Loader}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoaderAdapter() {
		if (loaderItemProvider == null) {
			loaderItemProvider = new LoaderItemProvider(this);
		}

		return loaderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ManyToAny} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManyToAnyItemProvider manyToAnyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ManyToAny}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManyToAnyAdapter() {
		if (manyToAnyItemProvider == null) {
			manyToAnyItemProvider = new ManyToAnyItemProvider(this);
		}

		return manyToAnyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ManyToMany} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManyToManyItemProvider manyToManyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ManyToMany}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManyToManyAdapter() {
		if (manyToManyItemProvider == null) {
			manyToManyItemProvider = new ManyToManyItemProvider(this);
		}

		return manyToManyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ManyToOne} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManyToOneItemProvider manyToOneItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ManyToOne}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManyToOneAdapter() {
		if (manyToOneItemProvider == null) {
			manyToOneItemProvider = new ManyToOneItemProvider(this);
		}

		return manyToOneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Map} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MapItemProvider mapItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Map}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMapAdapter() {
		if (mapItemProvider == null) {
			mapItemProvider = new MapItemProvider(this);
		}

		return mapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.MapKey} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MapKeyItemProvider mapKeyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.MapKey}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMapKeyAdapter() {
		if (mapKeyItemProvider == null) {
			mapKeyItemProvider = new MapKeyItemProvider(this);
		}

		return mapKeyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.MapKeyManyToMany} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MapKeyManyToManyItemProvider mapKeyManyToManyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.MapKeyManyToMany}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMapKeyManyToManyAdapter() {
		if (mapKeyManyToManyItemProvider == null) {
			mapKeyManyToManyItemProvider = new MapKeyManyToManyItemProvider(this);
		}

		return mapKeyManyToManyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Meta} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaItemProvider metaItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Meta}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaAdapter() {
		if (metaItemProvider == null) {
			metaItemProvider = new MetaItemProvider(this);
		}

		return metaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.MetaValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaValueItemProvider metaValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.MetaValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaValueAdapter() {
		if (metaValueItemProvider == null) {
			metaValueItemProvider = new MetaValueItemProvider(this);
		}

		return metaValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.NaturalId} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NaturalIdItemProvider naturalIdItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.NaturalId}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNaturalIdAdapter() {
		if (naturalIdItemProvider == null) {
			naturalIdItemProvider = new NaturalIdItemProvider(this);
		}

		return naturalIdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.NestedCompositeElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NestedCompositeElementItemProvider nestedCompositeElementItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.NestedCompositeElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNestedCompositeElementAdapter() {
		if (nestedCompositeElementItemProvider == null) {
			nestedCompositeElementItemProvider = new NestedCompositeElementItemProvider(this);
		}

		return nestedCompositeElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.OneToMany} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OneToManyItemProvider oneToManyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.OneToMany}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOneToManyAdapter() {
		if (oneToManyItemProvider == null) {
			oneToManyItemProvider = new OneToManyItemProvider(this);
		}

		return oneToManyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.OneToOne} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OneToOneItemProvider oneToOneItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.OneToOne}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOneToOneAdapter() {
		if (oneToOneItemProvider == null) {
			oneToOneItemProvider = new OneToOneItemProvider(this);
		}

		return oneToOneItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Param} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParamItemProvider paramItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Param}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParamAdapter() {
		if (paramItemProvider == null) {
			paramItemProvider = new ParamItemProvider(this);
		}

		return paramItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Parent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParentItemProvider parentItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Parent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParentAdapter() {
		if (parentItemProvider == null) {
			parentItemProvider = new ParentItemProvider(this);
		}

		return parentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.PrimitiveArray} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveArrayItemProvider primitiveArrayItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.PrimitiveArray}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveArrayAdapter() {
		if (primitiveArrayItemProvider == null) {
			primitiveArrayItemProvider = new PrimitiveArrayItemProvider(this);
		}

		return primitiveArrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Properties} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertiesItemProvider propertiesItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Properties}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertiesAdapter() {
		if (propertiesItemProvider == null) {
			propertiesItemProvider = new PropertiesItemProvider(this);
		}

		return propertiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Property} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyItemProvider propertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyAdapter() {
		if (propertyItemProvider == null) {
			propertyItemProvider = new PropertyItemProvider(this);
		}

		return propertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Query} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QueryItemProvider queryItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Query}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQueryAdapter() {
		if (queryItemProvider == null) {
			queryItemProvider = new QueryItemProvider(this);
		}

		return queryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.QueryParam} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QueryParamItemProvider queryParamItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.QueryParam}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQueryParamAdapter() {
		if (queryParamItemProvider == null) {
			queryParamItemProvider = new QueryParamItemProvider(this);
		}

		return queryParamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Resultset} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultsetItemProvider resultsetItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Resultset}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultsetAdapter() {
		if (resultsetItemProvider == null) {
			resultsetItemProvider = new ResultsetItemProvider(this);
		}

		return resultsetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Return} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnItemProvider returnItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Return}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnAdapter() {
		if (returnItemProvider == null) {
			returnItemProvider = new ReturnItemProvider(this);
		}

		return returnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnColumn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnColumnItemProvider returnColumnItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnColumn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnColumnAdapter() {
		if (returnColumnItemProvider == null) {
			returnColumnItemProvider = new ReturnColumnItemProvider(this);
		}

		return returnColumnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnDiscriminator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnDiscriminatorItemProvider returnDiscriminatorItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnDiscriminator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnDiscriminatorAdapter() {
		if (returnDiscriminatorItemProvider == null) {
			returnDiscriminatorItemProvider = new ReturnDiscriminatorItemProvider(this);
		}

		return returnDiscriminatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnJoin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnJoinItemProvider returnJoinItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnJoin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnJoinAdapter() {
		if (returnJoinItemProvider == null) {
			returnJoinItemProvider = new ReturnJoinItemProvider(this);
		}

		return returnJoinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnPropertyItemProvider returnPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnPropertyAdapter() {
		if (returnPropertyItemProvider == null) {
			returnPropertyItemProvider = new ReturnPropertyItemProvider(this);
		}

		return returnPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnScalar} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReturnScalarItemProvider returnScalarItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.ReturnScalar}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReturnScalarAdapter() {
		if (returnScalarItemProvider == null) {
			returnScalarItemProvider = new ReturnScalarItemProvider(this);
		}

		return returnScalarItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Set} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SetItemProvider setItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Set}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSetAdapter() {
		if (setItemProvider == null) {
			setItemProvider = new SetItemProvider(this);
		}

		return setItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.SqlDelete} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SqlDeleteItemProvider sqlDeleteItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.SqlDelete}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSqlDeleteAdapter() {
		if (sqlDeleteItemProvider == null) {
			sqlDeleteItemProvider = new SqlDeleteItemProvider(this);
		}

		return sqlDeleteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.SqlDeleteAll} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SqlDeleteAllItemProvider sqlDeleteAllItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.SqlDeleteAll}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSqlDeleteAllAdapter() {
		if (sqlDeleteAllItemProvider == null) {
			sqlDeleteAllItemProvider = new SqlDeleteAllItemProvider(this);
		}

		return sqlDeleteAllItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.SqlInsert} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SqlInsertItemProvider sqlInsertItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.SqlInsert}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSqlInsertAdapter() {
		if (sqlInsertItemProvider == null) {
			sqlInsertItemProvider = new SqlInsertItemProvider(this);
		}

		return sqlInsertItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.SqlQuery} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SqlQueryItemProvider sqlQueryItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.SqlQuery}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSqlQueryAdapter() {
		if (sqlQueryItemProvider == null) {
			sqlQueryItemProvider = new SqlQueryItemProvider(this);
		}

		return sqlQueryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.SqlUpdate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SqlUpdateItemProvider sqlUpdateItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.SqlUpdate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSqlUpdateAdapter() {
		if (sqlUpdateItemProvider == null) {
			sqlUpdateItemProvider = new SqlUpdateItemProvider(this);
		}

		return sqlUpdateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Subclass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubclassItemProvider subclassItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Subclass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubclassAdapter() {
		if (subclassItemProvider == null) {
			subclassItemProvider = new SubclassItemProvider(this);
		}

		return subclassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Synchronize} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SynchronizeItemProvider synchronizeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Synchronize}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSynchronizeAdapter() {
		if (synchronizeItemProvider == null) {
			synchronizeItemProvider = new SynchronizeItemProvider(this);
		}

		return synchronizeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Timestamp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimestampItemProvider timestampItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Timestamp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimestampAdapter() {
		if (timestampItemProvider == null) {
			timestampItemProvider = new TimestampItemProvider(this);
		}

		return timestampItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Tuplizer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TuplizerItemProvider tuplizerItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Tuplizer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTuplizerAdapter() {
		if (tuplizerItemProvider == null) {
			tuplizerItemProvider = new TuplizerItemProvider(this);
		}

		return tuplizerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Type} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypeItemProvider typeItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Type}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypeAdapter() {
		if (typeItemProvider == null) {
			typeItemProvider = new TypeItemProvider(this);
		}

		return typeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Typedef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TypedefItemProvider typedefItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Typedef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTypedefAdapter() {
		if (typedefItemProvider == null) {
			typedefItemProvider = new TypedefItemProvider(this);
		}

		return typedefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.UnionSubclass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnionSubclassItemProvider unionSubclassItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.UnionSubclass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnionSubclassAdapter() {
		if (unionSubclassItemProvider == null) {
			unionSubclassItemProvider = new UnionSubclassItemProvider(this);
		}

		return unionSubclassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.eclipse.emf.teneo.db2m.hbm30.Version} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VersionItemProvider versionItemProvider;

	/**
	 * This creates an adapter for a {@link org.eclipse.emf.teneo.db2m.hbm30.Version}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVersionAdapter() {
		if (versionItemProvider == null) {
			versionItemProvider = new VersionItemProvider(this);
		}

		return versionItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (anyItemProvider != null) anyItemProvider.dispose();
		if (arrayItemProvider != null) arrayItemProvider.dispose();
		if (bagItemProvider != null) bagItemProvider.dispose();
		if (cacheItemProvider != null) cacheItemProvider.dispose();
		if (classItemProvider != null) classItemProvider.dispose();
		if (collectionItemProvider != null) collectionItemProvider.dispose();
		if (collectionIdItemProvider != null) collectionIdItemProvider.dispose();
		if (columnItemProvider != null) columnItemProvider.dispose();
		if (componentItemProvider != null) componentItemProvider.dispose();
		if (compositeElementItemProvider != null) compositeElementItemProvider.dispose();
		if (compositeIdItemProvider != null) compositeIdItemProvider.dispose();
		if (compositeIndexItemProvider != null) compositeIndexItemProvider.dispose();
		if (compositeMapKeyItemProvider != null) compositeMapKeyItemProvider.dispose();
		if (databaseObjectItemProvider != null) databaseObjectItemProvider.dispose();
		if (definitionItemProvider != null) definitionItemProvider.dispose();
		if (dialectScopeItemProvider != null) dialectScopeItemProvider.dispose();
		if (discriminatorItemProvider != null) discriminatorItemProvider.dispose();
		if (dynamicComponentItemProvider != null) dynamicComponentItemProvider.dispose();
		if (elementItemProvider != null) elementItemProvider.dispose();
		if (filterItemProvider != null) filterItemProvider.dispose();
		if (filterDefItemProvider != null) filterDefItemProvider.dispose();
		if (filterParamItemProvider != null) filterParamItemProvider.dispose();
		if (generatorItemProvider != null) generatorItemProvider.dispose();
		if (hibernateMappingItemProvider != null) hibernateMappingItemProvider.dispose();
		if (idItemProvider != null) idItemProvider.dispose();
		if (idbagItemProvider != null) idbagItemProvider.dispose();
		if (importItemProvider != null) importItemProvider.dispose();
		if (indexItemProvider != null) indexItemProvider.dispose();
		if (indexManyToAnyItemProvider != null) indexManyToAnyItemProvider.dispose();
		if (indexManyToManyItemProvider != null) indexManyToManyItemProvider.dispose();
		if (joinItemProvider != null) joinItemProvider.dispose();
		if (joinedSubclassItemProvider != null) joinedSubclassItemProvider.dispose();
		if (keyItemProvider != null) keyItemProvider.dispose();
		if (keyManyToOneItemProvider != null) keyManyToOneItemProvider.dispose();
		if (keyPropertyItemProvider != null) keyPropertyItemProvider.dispose();
		if (listItemProvider != null) listItemProvider.dispose();
		if (listIndexItemProvider != null) listIndexItemProvider.dispose();
		if (loadCollectionItemProvider != null) loadCollectionItemProvider.dispose();
		if (loaderItemProvider != null) loaderItemProvider.dispose();
		if (manyToAnyItemProvider != null) manyToAnyItemProvider.dispose();
		if (manyToManyItemProvider != null) manyToManyItemProvider.dispose();
		if (manyToOneItemProvider != null) manyToOneItemProvider.dispose();
		if (mapItemProvider != null) mapItemProvider.dispose();
		if (mapKeyItemProvider != null) mapKeyItemProvider.dispose();
		if (mapKeyManyToManyItemProvider != null) mapKeyManyToManyItemProvider.dispose();
		if (metaItemProvider != null) metaItemProvider.dispose();
		if (metaValueItemProvider != null) metaValueItemProvider.dispose();
		if (naturalIdItemProvider != null) naturalIdItemProvider.dispose();
		if (nestedCompositeElementItemProvider != null) nestedCompositeElementItemProvider.dispose();
		if (oneToManyItemProvider != null) oneToManyItemProvider.dispose();
		if (oneToOneItemProvider != null) oneToOneItemProvider.dispose();
		if (paramItemProvider != null) paramItemProvider.dispose();
		if (parentItemProvider != null) parentItemProvider.dispose();
		if (primitiveArrayItemProvider != null) primitiveArrayItemProvider.dispose();
		if (propertiesItemProvider != null) propertiesItemProvider.dispose();
		if (propertyItemProvider != null) propertyItemProvider.dispose();
		if (queryItemProvider != null) queryItemProvider.dispose();
		if (queryParamItemProvider != null) queryParamItemProvider.dispose();
		if (resultsetItemProvider != null) resultsetItemProvider.dispose();
		if (returnItemProvider != null) returnItemProvider.dispose();
		if (returnColumnItemProvider != null) returnColumnItemProvider.dispose();
		if (returnDiscriminatorItemProvider != null) returnDiscriminatorItemProvider.dispose();
		if (returnJoinItemProvider != null) returnJoinItemProvider.dispose();
		if (returnPropertyItemProvider != null) returnPropertyItemProvider.dispose();
		if (returnScalarItemProvider != null) returnScalarItemProvider.dispose();
		if (setItemProvider != null) setItemProvider.dispose();
		if (sqlDeleteItemProvider != null) sqlDeleteItemProvider.dispose();
		if (sqlDeleteAllItemProvider != null) sqlDeleteAllItemProvider.dispose();
		if (sqlInsertItemProvider != null) sqlInsertItemProvider.dispose();
		if (sqlQueryItemProvider != null) sqlQueryItemProvider.dispose();
		if (sqlUpdateItemProvider != null) sqlUpdateItemProvider.dispose();
		if (subclassItemProvider != null) subclassItemProvider.dispose();
		if (synchronizeItemProvider != null) synchronizeItemProvider.dispose();
		if (timestampItemProvider != null) timestampItemProvider.dispose();
		if (tuplizerItemProvider != null) tuplizerItemProvider.dispose();
		if (typeItemProvider != null) typeItemProvider.dispose();
		if (typedefItemProvider != null) typedefItemProvider.dispose();
		if (unionSubclassItemProvider != null) unionSubclassItemProvider.dispose();
		if (versionItemProvider != null) versionItemProvider.dispose();
	}

}
