/**
 * <copyright>
 * </copyright>
 *
 * $Id: AddressValidator.java,v 1.1 2007/07/04 19:29:56 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.generaltest.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.teneo.samples.issues.generaltest.City;
import org.eclipse.emf.teneo.samples.issues.generaltest.Contact;
import org.eclipse.emf.teneo.samples.issues.generaltest.Country;
import org.eclipse.emf.teneo.samples.issues.generaltest.State;
import org.eclipse.emf.teneo.samples.issues.generaltest.TC;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.generaltest.Address}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AddressValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateContacts(EList<Contact> value);

	boolean validateState(State value);

	boolean validateCountry(Country value);

	boolean validateCity(City value);

	boolean validateTc(EList<TC> value);

	boolean validateTc(TC value);
}
