/**
 * <copyright>
 * </copyright>
 *
 * $Id: ContactValidator.java,v 1.1 2007/07/04 19:29:56 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.generaltest.validation;

import org.eclipse.emf.teneo.samples.issues.generaltest.Address;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.generaltest.Contact}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContactValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateAddress(Address value);
}
