/**
 * <copyright>
 * </copyright>
 *
 * $Id: ClaimLineCompositeKeyValidator.java,v 1.1 2008/01/18 06:20:17 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.claim.validation;

import org.eclipse.emf.teneo.samples.emf.sample.claim.Claim;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.claim.ClaimLineCompositeKey}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClaimLineCompositeKeyValidator {
	boolean validate();

	boolean validateClaim(Claim value);
	boolean validateClaimLineNumber(String value);
}
