/**
 * <copyright>
 * </copyright>
 *
 * $Id: PersonValidator.java,v 1.2 2010/02/06 20:50:47 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.hibernate.usertype.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.teneo.samples.emf.hibernate.usertype.Name;
import org.eclipse.emf.teneo.samples.emf.hibernate.usertype.UsaPhoneNumber;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.hibernate.usertype.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateName(Name value);
	boolean validateNumbers(int[] value);
	boolean validatePhoneNumbers(EList<?> value);
	boolean validateEmergencyContact(UsaPhoneNumber value);
	boolean validateAddresses(EList<?> value);
}
