/**
 * <copyright>
 * </copyright>
 *
 * $Id: ItemValidator.java,v 1.1 2007/02/08 23:09:23 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.set.validation;

import org.eclipse.emf.teneo.samples.emf.annotations.set.ItemList;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.set.Item}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ItemValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateItemList(ItemList value);
}
