/**
 * <copyright>
 * </copyright>
 *
 * $Id: BarValidator.java,v 1.1 2009/10/09 22:59:58 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.issues.bz284859.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.issues.bz284859.Bar}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BarValidator {
	boolean validate();

	boolean validateName(String value);
}
