/**
 * <copyright>
 * </copyright>
 *
 * $Id: ComplexTypeValidator.java,v 1.1 2009/07/27 22:12:04 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.schemaconstructs.documentroot.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.schemaconstructs.documentroot.ComplexType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexTypeValidator {
	boolean validate();

	boolean validateTest(String value);
}
