/**
 * <copyright>
 * </copyright>
 *
 * $Id: DocumentRootValidator.java,v 1.1 2007/02/08 23:09:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.play.validation;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

import org.eclipse.emf.teneo.samples.emf.sample.play.ActType;
import org.eclipse.emf.teneo.samples.emf.sample.play.FmType;
import org.eclipse.emf.teneo.samples.emf.sample.play.PersonaGroupType;
import org.eclipse.emf.teneo.samples.emf.sample.play.PersonaeType;
import org.eclipse.emf.teneo.samples.emf.sample.play.PlayType;
import org.eclipse.emf.teneo.samples.emf.sample.play.SceneType;
import org.eclipse.emf.teneo.samples.emf.sample.play.SpeechType;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.play.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap<String, String> value);
	boolean validateXSISchemaLocation(EMap<String, String> value);
	boolean validateAct(ActType value);
	boolean validateFm(FmType value);
	boolean validateGroupDescription(String value);
	boolean validateLine(String value);
	boolean validateP(String value);
	boolean validatePersona(String value);
	boolean validatePersonae(PersonaeType value);
	boolean validatePersonaGroup(PersonaGroupType value);
	boolean validatePlay(PlayType value);
	boolean validatePlaySubTitle(String value);
	boolean validateScene(SceneType value);
	boolean validateSceneDescription(String value);
	boolean validateSpeaker(String value);
	boolean validateSpeech(SpeechType value);
	boolean validateStageDirections(String value);
	boolean validateTitle(String value);
}
