/**
 * <copyright>
 * </copyright>
 *
 * $Id: PlayTypeValidator.java,v 1.1 2007/02/08 23:09:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.play.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.samples.emf.sample.play.ActType;
import org.eclipse.emf.teneo.samples.emf.sample.play.FmType;
import org.eclipse.emf.teneo.samples.emf.sample.play.PersonaeType;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.play.PlayType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlayTypeValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateFm(FmType value);
	boolean validatePersonae(PersonaeType value);
	boolean validateSceneDescription(String value);
	boolean validatePlaySubTitle(String value);
	boolean validateAct(EList<ActType> value);
}
