/**
 * <copyright>
 * </copyright>
 *
 * $Id: SpeechTypeValidator.java,v 1.1 2007/02/08 23:09:24 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.sample.play.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.sample.play.SpeechType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpeechTypeValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateSpeaker(EList<String> value);
	boolean validateLine(EList<String> value);
	boolean validateStageDirections(EList<String> value);
}
