/**
 * <copyright>
 * </copyright>
 *
 * $Id: PenValidator.java,v 1.1 2009/09/11 15:38:41 mtaal Exp $
 */
package org.eclipse.emf.teneo.samples.emf.annotations.eavlibrary.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.samples.emf.annotations.eavlibrary.Pen}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PenValidator {
	boolean validate();

	boolean validateName(String value);
}
