/**
 * <copyright>
 * </copyright>
 *
 * $Id: NoteValidator.java,v 1.1 2009/08/23 16:04:40 mtaal Exp $
 */
package org.eclipse.emf.test.databinding.emfdb.validation;

/**
 * A sample validator interface for {@link org.eclipse.emf.test.databinding.emfdb.Note}. This
 * doesn't really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NoteValidator {
	boolean validate();

	boolean validateName(String value);
}
