/**
 * <copyright>
 * </copyright>
 *
 * $Id: PersonValidator.java,v 1.1 2009/08/23 16:04:40 mtaal Exp $
 */
package org.eclipse.emf.test.databinding.emfdb.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.test.databinding.emfdb.Note;
import org.eclipse.emf.test.databinding.emfdb.Person;

/**
 * A sample validator interface for {@link org.eclipse.emf.test.databinding.emfdb.Person}. This
 * doesn't really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateNotes(EList<Note> value);

	boolean validateParents(EList<Person> value);
}
